# Generated by Django 6.0.6 on 2026-07-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('cdd_echeance', 'CDD/Stage — échéance proche'), ('fin_essai', "Fin de période d'essai proche")], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.CharField(max_length=300, verbose_name='Message')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='Lien vers la page concernée')),
                ('cle', models.CharField(help_text='Empêche de dupliquer la même alerte (ex: type + id salarié + date).', max_length=200, unique=True, verbose_name="Clé d'unicité")),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
