# Generated by Django 6.0.6 on 2026-07-19 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du pôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('modules_ids', models.JSONField(default=list, help_text="Clés des modules métier (ex: ['social-rh']) que ce pôle peut voir.", verbose_name='Modules accessibles')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poles_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du pôle')),
            ],
            options={
                'verbose_name': 'Pôle',
                'verbose_name_plural': 'Pôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='pilotage.pole', verbose_name='Pôle')),
                ('poste_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_subordonnes', to='pilotage.poste', verbose_name='Rattaché à (poste hiérarchique supérieur)')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['pole__nom', 'intitule'],
            },
        ),
    ]
