# Generated by Django 6.0.6 on 2026-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0002_pole_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='fonctionnalites_urls',
            field=models.JSONField(default=list, help_text="Accès à une action précise (ex: 'Nouveau devis'), comme un outil isolé.", verbose_name='Fonctionnalités accessibles'),
        ),
        migrations.AddField(
            model_name='pole',
            name='sous_modules_urls',
            field=models.JSONField(default=list, help_text='Accès à un sous-module précis, sans donner tout le module.', verbose_name='Sous-modules accessibles'),
        ),
    ]
