# Generated by Django 6.0.6 on 2026-07-20 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0005_alter_notification_type_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(blank=True, help_text='Si vide, notification générale (visible par tous, comme avant). Si rempli, visible par ce destinataire précis + toujours par Direction/Cadre.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL),
        ),
    ]
