# Generated by Django 6.0.6 on 2026-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotage', '0006_notification_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('cdd_echeance', 'CDD/Stage — échéance proche'), ('fin_essai', "Fin de période d'essai proche"), ('relance_notification_interne', 'Recouvrement — notification interne'), ('relance_escalade_direction', 'Recouvrement — escalade Direction'), ('relance_alerte_contentieux', 'Recouvrement — alerte contentieux'), ('promesse_rompue', 'Recouvrement — promesse rompue'), ('budget_alerte', 'Budget — seuil atteint')], max_length=30, verbose_name='Type'),
        ),
    ]
