# Generated by Django 6.0.6 on 2026-07-20 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONSULTATION', 'Consultation'), ('EXPORT', 'Export'), ('ACTION_METIER', 'Action métier')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_journa_content_b1c62f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoteInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Note interne',
                'verbose_name_plural': 'Notes internes',
                'ordering': ['date_creation'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_notein_content_f65e17_idx')],
            },
        ),
    ]
