# Generated by Django 6.0.6 on 2026-07-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalExecutionCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('objet', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.CharField(choices=[('EN_COURS', 'En cours'), ('SUCCES', 'Succès'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=20)),
                ('resume', models.TextField(blank=True)),
                ('erreur', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.FloatField(default=0.0)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution de commande',
                'verbose_name_plural': 'Exécutions de commandes',
                'ordering': ['-date_debut'],
            },
        ),
    ]
