# Generated by Django 6.0.6 on 2026-07-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conversation', models.CharField(choices=[('direct', 'Conversation directe (à deux)'), ('groupe', 'Groupe')], default='direct', max_length=10, verbose_name='Type')),
                ('nom', models.CharField(blank=True, default='', help_text='Utilisé uniquement pour un groupe.', max_length=150, verbose_name='Nom du groupe')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, default='', verbose_name='Message')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messagerie/%Y/%m/', verbose_name='Pièce jointe')),
                ('nom_fichier_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversation')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_admin', models.BooleanField(default=False, verbose_name='Administrateur du groupe')),
                ('rejoint_le', models.DateTimeField(auto_now_add=True, verbose_name='A rejoint le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='messagerie.conversation')),
                ('dernier_message_lu', models.ForeignKey(blank=True, help_text='Sert à calculer le nombre de messages non lus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messagerie.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'unique_together': {('conversation', 'utilisateur')},
            },
        ),
    ]
