# Generated by Django 6.0.6 on 2026-07-19 21:15

import django.core.validators
import messagerie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rappel_expiration_envoye',
            field=models.BooleanField(default=False, verbose_name='Rappel de suppression envoyé'),
        ),
        migrations.AlterField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messagerie/%Y/%m/', validators=[messagerie.models.valider_taille_fichier], verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='message',
            name='texte',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Message'),
        ),
    ]
