# Generated by Django 6.0.6 on 2026-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_message_rappel_expiration_envoye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cle_reunion',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Clé de la salle de réunion'),
        ),
        migrations.AddField(
            model_name='message',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='message',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
