# Generated by Django 6.0.6 on 2026-06-29 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet de la demande')),
                ('siege', models.CharField(choices=[('DALOA', 'Daloa'), ('BASSAM', 'Grand-Bassam')], max_length=10, verbose_name='Siège souhaité')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('TRAITEE', 'Traitée')], default='NOUVELLE', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reçue le')),
            ],
            options={
                'verbose_name': 'Demande de rendez-vous',
                'verbose_name_plural': 'Demandes de rendez-vous',
                'ordering': ['-date_creation'],
            },
        ),
    ]
