# Generated by Django 6.0.6 on 2026-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderendezvous',
            name='objet',
            field=models.CharField(choices=[('COMPTABILITE', 'Comptabilité'), ('FISCALITE', 'Fiscalité'), ('AUDIT', 'Audit'), ('RH', 'Ressources humaines'), ('FORMATION', 'Formation'), ('CONSEIL', 'Conseil'), ('ORGANISATION', 'Organisation & stratégie'), ('AIDES', 'Aides publiques et privées'), ('RENSEIGNEMENTS', 'Renseignements généraux'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Objet de la demande'),
        ),
    ]
