# Generated by Django 6.0.6 on 2026-06-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_alter_demanderendezvous_objet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanderendezvous',
            name='objet',
        ),
        migrations.RemoveField(
            model_name='demanderendezvous',
            name='siege',
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='anciennete',
            field=models.CharField(blank=True, choices=[('PROJET', 'Projet non lancé'), ('MOINS_1AN', "Moins d'un an"), ('UN_A_TROIS', '1 à 3 ans'), ('PLUS_3ANS', 'Plus de 3 ans')], max_length=20, verbose_name="Ancienneté de l'activité"),
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='cabinet_actuel',
            field=models.BooleanField(default=False, verbose_name='A déjà un cabinet comptable'),
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='chiffre_affaires',
            field=models.CharField(blank=True, choices=[('MOINS_50M', 'Moins de 50 millions FCFA'), ('DE_50_200M', '50 à 200 millions FCFA'), ('DE_200_500M', '200 à 500 millions FCFA'), ('PLUS_500M', 'Plus de 500 millions FCFA'), ('INCONNU', 'Je ne sais pas encore')], max_length=20, verbose_name="Chiffre d'affaires prévisionnel"),
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='lieu',
            field=models.CharField(choices=[('DALOA', 'Daloa (siège)'), ('BASSAM', 'Grand-Bassam (succursale)')], default='DALOA', max_length=10, verbose_name='Lieu de rendez-vous souhaité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='motifs',
            field=models.CharField(default='DALOA', help_text='Un ou plusieurs domaines, séparés par des virgules.', max_length=300, verbose_name='Objet(s) de la demande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='secteur',
            field=models.CharField(blank=True, max_length=150, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='demanderendezvous',
            name='structure',
            field=models.CharField(blank=True, choices=[('INDIVIDUELLE', 'Entreprise individuelle'), ('SARL', 'SARL'), ('SA', 'SA'), ('ASSOCIATION', 'Association'), ('ONG', 'ONG'), ('COOPERATIVE', 'Coopérative'), ('PARTICULIER', 'Particulier'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de structure'),
        ),
    ]
