# Generated by Django 6.0.6 on 2026-06-30 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelTelephonique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_appelant', models.CharField(max_length=150, verbose_name="Nom de l'appelant")),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('date_appel', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de l'appel")),
                ('objet', models.TextField(verbose_name="Objet de l'appel")),
                ('a_rappeler', models.BooleanField(default=False, verbose_name='À rappeler')),
                ('date_rappel', models.DateField(blank=True, null=True, verbose_name='Date de rappel souhaitée')),
                ('statut', models.CharField(choices=[('A_TRAITER', 'À traiter'), ('TRAITE', 'Traité')], default='A_TRAITER', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Appel téléphonique',
                'verbose_name_plural': 'Appels téléphoniques',
                'ordering': ['-date_appel'],
            },
        ),
    ]
