# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la catégorie')),
                ('regime', models.CharField(choices=[('RECURRENTE', 'Récurrente (suivi régulier)'), ('PONCTUELLE', 'Ponctuelle (prestation unique)')], default='RECURRENTE', max_length=12, verbose_name='Régime')),
            ],
            options={
                'verbose_name': 'Catégorie de prestation',
                'verbose_name_plural': 'Catégories de prestations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PrestationCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé de la prestation')),
                ('prix_par_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire par défaut (FCFA)')),
                ('periodicite', models.CharField(blank=True, help_text='Ex : Mensuel, Trimestriel, Annuel, Ponctuel', max_length=50, verbose_name='Périodicité')),
                ('taux_tva', models.CharField(choices=[('18', 'TVA 18% (taux normal)'), ('9', 'TVA 9% (taux réduit)'), ('0', 'Exonéré (0%)')], default='18', max_length=2, verbose_name='Taux de TVA')),
                ('delai_livraison', models.CharField(blank=True, help_text='Ex : 15 jours ouvrés à compter de la réception des pièces', max_length=100, verbose_name='Délai de livraison')),
                ('livrable', models.CharField(blank=True, help_text="Ex : États financiers annuels, rapport d'audit…", max_length=255, verbose_name='Livrable (document à remettre)')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='parametres.categorieprestation', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['libelle'],
            },
        ),
    ]
