# Generated by Django 6.0.6 on 2026-06-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestationcatalogue',
            name='prix_par_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de base (si pas de variantes, FCFA)'),
        ),
        migrations.CreateModel(
            name='VariantePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex : 1 à 5 salariés, RNI, CA < 50M, secteur BTP…', max_length=150, verbose_name='Critère / tranche')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='parametres.prestationcatalogue', verbose_name='Prestation')),
            ],
            options={
                'verbose_name': 'Variante de prix',
                'verbose_name_plural': 'Variantes de prix',
                'ordering': ['prix'],
            },
        ),
    ]
