# Generated by Django 6.0.6 on 2026-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_alter_prestationcatalogue_prix_par_defaut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresLettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_recurrente_mois', models.PositiveIntegerField(default=12, help_text='Durée initiale avant tacite reconduction', verbose_name='Durée des missions récurrentes (mois)')),
                ('preavis_mois', models.PositiveIntegerField(default=3, verbose_name='Préavis de résiliation (mois)')),
                ('modalites_paiement_defaut', models.CharField(blank=True, default='Les honoraires sont payables mensuellement, au plus tard le 5 de chaque mois', max_length=255, verbose_name='Modalités de paiement par défaut')),
                ('delai_paiement_ponctuel', models.CharField(blank=True, default='Les honoraires sont payables à la remise des livrables', max_length=255, verbose_name='Modalités de paiement (missions ponctuelles)')),
            ],
            options={
                'verbose_name': 'Paramètres de la lettre de mission',
                'verbose_name_plural': 'Paramètres de la lettre de mission',
            },
        ),
    ]
