# Generated by Django 6.0.6 on 2026-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_parametreslettre'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationcatalogue',
            name='duree_engagement_mois',
            field=models.PositiveIntegerField(default=12, help_text='Durée initiale avant tacite reconduction. Ignoré pour le ponctuel.', verbose_name="Durée d'engagement (mois) — pour le régime récurrent"),
        ),
        migrations.AddField(
            model_name='prestationcatalogue',
            name='modalites_paiement',
            field=models.CharField(blank=True, help_text='Ex : mensuels payables le 5 / à la remise des livrables', max_length=255, verbose_name='Modalités de paiement'),
        ),
        migrations.AddField(
            model_name='prestationcatalogue',
            name='preavis_mois',
            field=models.PositiveIntegerField(default=3, help_text='Ignoré pour le ponctuel.', verbose_name='Préavis de résiliation (mois) — pour le régime récurrent'),
        ),
    ]
