# Generated by Django 6.0.6 on 2026-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_delete_parametreslettre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_envoi', models.EmailField(blank=True, help_text="L'adresse qui enverra les emails", max_length=254, verbose_name="Adresse Gmail d'envoi")),
                ('mot_de_passe_app', models.CharField(blank=True, help_text='Code généré par Google, pas le mot de passe Gmail habituel', max_length=100, verbose_name="Mot de passe d'application (16 caractères)")),
                ('nom_expediteur', models.CharField(blank=True, default='Cabinet K&L', help_text="Ex : Cabinet K&L — apparaît comme nom de l'expéditeur", max_length=120, verbose_name="Nom de l'expéditeur")),
            ],
            options={
                'verbose_name': 'Paramètres email',
                'verbose_name_plural': 'Paramètres email',
            },
        ),
    ]
