# Generated by Django 6.0.6 on 2026-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_parametresemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, verbose_name="Texte des conditions d'utilisation")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Conditions d'utilisation",
                'verbose_name_plural': "Conditions d'utilisation",
            },
        ),
    ]
