# Generated by Django 6.0.6 on 2026-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_conditionsutilisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresFNE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_base', models.CharField(blank=True, help_text="URL de l'API FNE pour la certification des factures.", max_length=255, verbose_name="URL de l'API FNE")),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='Login API FNE')),
                ('cle_api', models.CharField(blank=True, help_text="Clé ou token fourni par la DGI pour l'accès à l'API FNE.", max_length=255, verbose_name='Clé API FNE')),
                ('code_societe', models.CharField(blank=True, help_text="Code de l'entreprise ou du cabinet dans le système FNE.", max_length=50, verbose_name='Code société')),
                ('certificat_actif', models.BooleanField(default=False, verbose_name='Certification FNE activée')),
            ],
            options={
                'verbose_name': 'Paramètres FNE',
                'verbose_name_plural': 'Paramètres FNE',
            },
        ),
    ]
