# Generated by Django 6.0.6 on 2026-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_parametresfne'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresfne',
            name='api_key',
            field=models.CharField(blank=True, help_text="Clé ou token fourni par la DGI pour l'accès à l'API FNE.", max_length=255, verbose_name='Clé API FNE'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='environnement',
            field=models.CharField(choices=[('TEST', 'Test'), ('PROD', 'Production')], default='TEST', max_length=10, verbose_name='Environnement FNE'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='etablissement_defaut',
            field=models.CharField(blank=True, help_text='Valeur utilisée pour les factures FNE sans établissement défini.', max_length=150, verbose_name='Établissement par défaut'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='ncc_cabinet',
            field=models.CharField(blank=True, help_text="Numéro de déclaration de l'entreprise ou du cabinet.", max_length=50, verbose_name='NCC du cabinet'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='point_de_vente_defaut',
            field=models.CharField(blank=True, help_text='Valeur utilisée pour les factures FNE sans point de vente défini.', max_length=150, verbose_name='Point de vente par défaut'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='url_production',
            field=models.URLField(blank=True, help_text="URL de l'environnement de production de l'API FNE.", max_length=255, verbose_name='URL de production FNE'),
        ),
        migrations.AddField(
            model_name='parametresfne',
            name='url_test',
            field=models.URLField(blank=True, help_text="URL de l'environnement de test de l'API FNE.", max_length=255, verbose_name='URL de test FNE'),
        ),
    ]
