# Generated by Django 6.0.6 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_parametresfne_api_key_parametresfne_environnement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametresfne',
            options={'verbose_name': 'Paramètres FNE (DGI)', 'verbose_name_plural': 'Paramètres FNE (DGI)'},
        ),
        migrations.RemoveField(
            model_name='parametresfne',
            name='certificat_actif',
        ),
        migrations.RemoveField(
            model_name='parametresfne',
            name='cle_api',
        ),
        migrations.RemoveField(
            model_name='parametresfne',
            name='code_societe',
        ),
        migrations.RemoveField(
            model_name='parametresfne',
            name='login',
        ),
        migrations.RemoveField(
            model_name='parametresfne',
            name='url_base',
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='api_key',
            field=models.CharField(blank=True, help_text="Visible uniquement par le gestionnaire principal, dans l'onglet « Paramétrage » de l'espace FNE, une fois l'interfaçage validé par la DGI", max_length=255, verbose_name='Clé API (Bearer token)'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='environnement',
            field=models.CharField(choices=[('TEST', 'Environnement de test'), ('PROD', 'Environnement de production')], default='TEST', max_length=5, verbose_name='Environnement actif'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='etablissement_defaut',
            field=models.CharField(blank=True, max_length=150, verbose_name='Établissement par défaut'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='ncc_cabinet',
            field=models.CharField(blank=True, max_length=20, verbose_name='NCC du cabinet (émetteur)'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='point_de_vente_defaut',
            field=models.CharField(blank=True, help_text='Utilisé pour pré-remplir les nouvelles factures', max_length=150, verbose_name='Point de vente par défaut'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='url_production',
            field=models.URLField(blank=True, help_text="Transmise par la DGI par email, après validation de l'interfaçage", verbose_name='URL de production'),
        ),
        migrations.AlterField(
            model_name='parametresfne',
            name='url_test',
            field=models.URLField(default='http://54.247.95.108/ws', help_text="Fournie par la DGI — normalement pas besoin d'y toucher", verbose_name="URL de l'environnement de test"),
        ),
    ]
