# Generated by Django 6.0.6 on 2026-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_alter_parametresfne_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_environnement', models.CharField(choices=[('TEST', 'Environnement de test'), ('PROD', 'Environnement de production')], default='TEST', max_length=5, verbose_name='Wave — Environnement actif')),
                ('wave_api_key', models.CharField(blank=True, help_text='Format wave_sn_test_... ou wave_sn_prod_..., générée dans le portail Wave Business', max_length=255, verbose_name='Wave — Clé API (Bearer token)')),
                ('wave_webhook_secret', models.CharField(blank=True, help_text="Utilisé pour vérifier l'authenticité des notifications reçues de Wave", max_length=255, verbose_name='Wave — Secret webhook')),
                ('om_environnement', models.CharField(choices=[('TEST', 'Environnement de test'), ('PROD', 'Environnement de production')], default='TEST', max_length=5, verbose_name='Orange Money — Environnement actif')),
                ('om_client_id', models.CharField(blank=True, help_text="Fourni par Orange Developer lors de l'inscription au service Web Payment", max_length=255, verbose_name='Orange Money — Client ID')),
                ('om_client_secret', models.CharField(blank=True, max_length=255, verbose_name='Orange Money — Client Secret')),
                ('om_merchant_key', models.CharField(blank=True, help_text='Distincte du client_id/secret — fournie séparément par Orange', max_length=255, verbose_name='Orange Money — Clé marchand')),
                ('om_return_url', models.URLField(blank=True, verbose_name='Orange Money — URL de retour (paiement réussi)')),
                ('om_cancel_url', models.URLField(blank=True, verbose_name="Orange Money — URL d'annulation")),
                ('om_notif_url', models.URLField(blank=True, help_text="URL de ce serveur qu'Orange appellera pour confirmer un paiement", verbose_name='Orange Money — URL de notification (webhook)')),
            ],
            options={
                'verbose_name': 'Paramètres Mobile Money (Wave / Orange Money)',
                'verbose_name_plural': 'Paramètres Mobile Money (Wave / Orange Money)',
            },
        ),
        migrations.CreateModel(
            name='ParametresWhatsAppBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, help_text='Idéalement un token permanent généré via un utilisateur système', max_length=512, verbose_name='Access Token')),
                ('phone_number_id', models.CharField(blank=True, help_text='Identifiant technique Meta du numéro WhatsApp', max_length=50, verbose_name='Phone Number ID')),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Business Account ID (WABA)')),
                ('app_id', models.CharField(blank=True, max_length=50, verbose_name='App ID (Meta for Developers)')),
                ('app_secret', models.CharField(blank=True, max_length=255, verbose_name='App Secret')),
                ('verify_token', models.CharField(blank=True, help_text='Chaîne inventée par le cabinet, à renseigner aussi côté Meta', max_length=255, verbose_name='Verify Token (webhook)')),
            ],
            options={
                'verbose_name': 'Paramètres WhatsApp Business',
                'verbose_name_plural': 'Paramètres WhatsApp Business',
            },
        ),
    ]
