# Generated by Django 6.0.6 on 2026-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0011_parametresmobilemoney_parametreswhatsappbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresmobilemoney',
            name='wave_signature_activee',
            field=models.BooleanField(default=False, help_text='⚠️ Une fois activée sur une clé API (côté portail Wave), elle ne peut plus être désactivée sans révoquer la clé et en recréer une nouvelle', verbose_name='Wave — Signature des requêtes activée'),
        ),
        migrations.AddField(
            model_name='parametresmobilemoney',
            name='wave_signing_secret',
            field=models.CharField(blank=True, help_text='Format wave_sn_AKS_... — affiché une seule fois à la création de la clé API si la signature est activée. Sert à signer nos requêtes sortantes (en-tête Wave-Signature), pas à vérifier les webhooks entrants.', max_length=255, verbose_name='Wave — Secret de signature (HMAC)'),
        ),
        migrations.AlterField(
            model_name='parametresmobilemoney',
            name='wave_api_key',
            field=models.CharField(blank=True, help_text='Format wave_sn_test_... ou wave_sn_prod_..., générée dans le portail Wave Business, section Développeurs', max_length=255, verbose_name='Wave — Clé API (Bearer token)'),
        ),
    ]
