# Generated by Django 6.0.6 on 2026-06-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_acces', models.EmailField(max_length=254, verbose_name='Email de réception des accès')),
                ('lettre_mission', models.FileField(blank=True, null=True, upload_to='lettres_mission/', verbose_name='Lettre de mission signée')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'activation"), ('A_VERIFIER', "En attente de vérification d'identité"), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('code_client', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code client')),
                ('date_entree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée au cabinet")),
                ('gestionnaire', models.CharField(blank=True, max_length=100, verbose_name='Gestionnaire attitré')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('devis_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_crees', to='devis.devis', verbose_name="Devis d'origine")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_entree'],
            },
        ),
    ]
