# Generated by Django 6.0.6 on 2026-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='ncc',
            field=models.CharField(blank=True, max_length=20, verbose_name='N° Compte Contribuable (NCC)'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom / Raison sociale'),
        ),
        migrations.AddField(
            model_name='client',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(blank=True, choices=[('PP_INFORMEL', 'Personne Physique — secteur informel'), ('PP_CONSTITUEE', 'Personne Physique légalement constituée'), ('PM', 'Personne Morale')], max_length=20, verbose_name='Type de client'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_acces',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de réception des accès'),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE', "En attente d'activation"), ('A_VERIFIER', "En attente de vérification d'identité"), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé')], default='EN_PREPARATION', max_length=15, verbose_name='Statut'),
        ),
    ]
