# Generated by Django 6.0.6 on 2026-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_commune_client_email_client_ncc_client_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_entreprise',
            field=models.ImageField(blank=True, null=True, upload_to='logos_clients/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='client',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations sur le client'),
        ),
        migrations.AddField(
            model_name='client',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, verbose_name="Slogan de l'entreprise"),
        ),
        migrations.AddField(
            model_name='client',
            name='user_principal_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Utilisateur principal — Nom et prénoms'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_principal_piece_nature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Utilisateur principal — Nature de la pièce'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_principal_piece_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Utilisateur principal — N° de la pièce'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_principal_qualite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Utilisateur principal — Qualité'),
        ),
    ]
