# Generated by Django 6.0.6 on 2026-06-30 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_logo_entreprise_client_observations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_lie', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion'),
        ),
    ]
