# Generated by Django 6.0.6 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cgv_acceptees',
            field=models.BooleanField(default=False, verbose_name='CGV acceptées'),
        ),
        migrations.AddField(
            model_name='client',
            name='lettre_confirmee',
            field=models.BooleanField(default=False, verbose_name='Lettre de mission confirmée'),
        ),
        migrations.AddField(
            model_name='client',
            name='mdp_change',
            field=models.BooleanField(default=False, verbose_name='Mot de passe changé'),
        ),
    ]
