# Generated by Django 6.0.6 on 2026-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_cgv_acceptees_client_lettre_confirmee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE', "En attente d'activation"), ('A_VERIFIER', "En attente de vérification d'identité"), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé')], default='EN_PREPARATION', max_length=25, verbose_name='Statut'),
        ),
    ]
