# Generated by Django 6.0.6 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consentement_signature_electronique',
            field=models.BooleanField(default=False, verbose_name='Consentement signature électronique'),
        ),
    ]
