# Generated by Django 6.0.6 on 2026-06-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, verbose_name='Matricule')),
                ('civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=5, verbose_name='Civilité')),
                ('nom_prenoms', models.CharField(max_length=200, verbose_name='Noms & Prénoms')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('nature_piece', models.CharField(blank=True, max_length=50, verbose_name="Nature pièce d'identité")),
                ('numero_piece', models.CharField(blank=True, max_length=50, verbose_name="Numéro pièce d'identité")),
                ('nationalite', models.CharField(default='IVOIRIENNE', max_length=100, verbose_name='Nationalité')),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)')], default='celibataire', max_length=15, verbose_name='Situation matrimoniale')),
                ('nombre_enfants', models.IntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('lieu_habitation', models.CharField(blank=True, max_length=150, verbose_name="Lieu d'habitation")),
                ('contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage')], default='CDI', max_length=10, verbose_name='Type de contrat')),
                ('date_signature_contrat', models.DateField(blank=True, null=True, verbose_name='Date de signature du contrat')),
                ('duree_cdd_mois', models.IntegerField(blank=True, null=True, verbose_name='Durée CDD (mois)')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('direction', models.CharField(blank=True, max_length=100, verbose_name='Direction')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('emploi', models.CharField(blank=True, max_length=100, verbose_name='Emploi')),
                ('code_emploi', models.CharField(blank=True, max_length=30, verbose_name='Code emploi')),
                ('regime', models.CharField(choices=[('general', 'Général'), ('agricole', 'Agricole'), ('expatrie', 'Expatrié')], default='general', max_length=15, verbose_name='Régime')),
                ('categorie', models.CharField(blank=True, max_length=20, verbose_name='Catégorie')),
                ('type_salaire', models.CharField(choices=[('mensuel', 'Mensuel'), ('journalier', 'Journalier')], default='mensuel', max_length=15, verbose_name='Type de salaire')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base (FCFA)')),
                ('non_soumis_cnps', models.BooleanField(default=False, verbose_name='Non soumis à la CNPS')),
                ('numero_cnps', models.CharField(blank=True, max_length=30, verbose_name='N° CNPS')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], default='virement', max_length=15, verbose_name='Mode de paiement')),
                ('numero_compte', models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte bancaire')),
                ('banque', models.CharField(blank=True, max_length=100, verbose_name='Banque')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SORTI', 'Sorti'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom_prenoms'],
            },
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du secteur')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('taux_at', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Taux Accident de Travail du secteur (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('jours_travailles', models.DecimalField(decimal_places=1, default=30, max_digits=4, verbose_name='Jours travaillés')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base')),
                ('heures_sup', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Heures supplémentaires (montant)')),
                ('prime_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prime de transport')),
                ('conge_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Congé payé')),
                ('gratification', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gratification')),
                ('preavis', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Préavis')),
                ('indemnite_licenciement', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemnité de licenciement')),
                ('indemnite_transactionnelle', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemnité transactionnelle de rupture')),
                ('frais_funeraires', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais funéraires')),
                ('avance_acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avance / Acompte')),
                ('montant_pret', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remboursement de prêt')),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres retenues')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='Sigle')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('boite_postale', models.CharField(blank=True, max_length=50, verbose_name='Boîte postale')),
                ('centre_impots', models.CharField(blank=True, max_length=100, verbose_name='Centre des impôts')),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='RCCM N°')),
                ('ncc', models.CharField(blank=True, max_length=20, verbose_name='NCC')),
                ('numero_cnps', models.CharField(blank=True, max_length=30, verbose_name='N° employeur CNPS')),
                ('signataire_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du signataire')),
                ('signataire_qualite', models.CharField(blank=True, max_length=100, verbose_name='Qualité du signataire')),
                ('jours_conges_par_mois', models.DecimalField(decimal_places=2, default=2.2, max_digits=4, verbose_name='Jours de congés acquis par mois')),
                ('plafond_transport_exonere', models.DecimalField(decimal_places=2, default=30000, max_digits=10, verbose_name='Montant exonéré prime de transport (FCFA)')),
                ('arrondi_net', models.IntegerField(choices=[(1, 'Au franc près'), (5, 'Aux 5 F'), (10, 'Aux 10 F'), (100, 'Aux 100 F')], default=5, verbose_name='Arrondi du net à payer')),
                ('est_cabinet', models.BooleanField(default=False, verbose_name='Est le cabinet lui-même')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeur', to='clients.client', verbose_name='Client rattaché (laisser vide si cabinet ou externe)')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeurs', to='paie.secteuractivite', verbose_name="Secteur d'activité")),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='paie.employeur', verbose_name='Employeur'),
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banques', to='paie.employeur', verbose_name='Employeur')),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques (par entreprise)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametrePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_cnps_retraite_salarie', models.DecimalField(decimal_places=2, default=6.3, max_digits=5, verbose_name='CNPS Retraite - part salarié (%)')),
                ('taux_cnps_retraite_employeur', models.DecimalField(decimal_places=2, default=7.7, max_digits=5, verbose_name='CNPS Retraite - part employeur (%)')),
                ('taux_cnps_pf', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='CNPS Prestations Familiales (%)')),
                ('taux_cnps_maternite', models.DecimalField(decimal_places=2, default=0.75, max_digits=5, verbose_name='CNPS Assurance Maternité (%)')),
                ('plafond_cnps', models.DecimalField(decimal_places=2, default=3375000, max_digits=12, verbose_name='Plafond mensuel CNPS (FCFA)')),
                ('taux_fdfp_ta', models.DecimalField(decimal_places=2, default=0.4, max_digits=5, verbose_name="FDFP Taxe d'Apprentissage (%)")),
                ('taux_fdfp_fpc', models.DecimalField(decimal_places=2, default=0.6, max_digits=5, verbose_name='FDFP Formation Prof. Continue (%)')),
                ('montant_cmu', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='CMU (forfait par personne, FCFA)')),
                ('employeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='paie.employeur', verbose_name='Employeur')),
            ],
            options={
                'verbose_name': 'Paramètre de paie',
                'verbose_name_plural': 'Paramètres de paie',
            },
        ),
        migrations.CreateModel(
            name='PrimeConfiguree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé de la prime')),
                ('traitement_fiscal', models.CharField(choices=[('exonere', 'Exonéré (ni impôt ni cotisation)'), ('imposable', 'Imposable / cotisable à 100%'), ('abattement', 'Imposable après abattement de 10%')], default='imposable', max_length=12, verbose_name='Nature fiscale')),
                ('soumis_cnps', models.BooleanField(default=True, verbose_name='Soumise à la CNPS')),
                ('montant_par_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant par défaut (modifiable, FCFA)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes_configurees', to='paie.employeur', verbose_name='Employeur')),
            ],
            options={
                'verbose_name': 'Prime configurée',
                'verbose_name_plural': 'Primes configurées (par entreprise)',
                'ordering': ['employeur', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='LignePrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé de la prime')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('traitement_fiscal', models.CharField(choices=[('exonere', 'Exonéré (ni impôt ni cotisation)'), ('imposable', 'Imposable / cotisable à 100%'), ('abattement', 'Imposable après abattement de 10%')], default='imposable', max_length=12, verbose_name='Traitement fiscal (ITS)')),
                ('soumis_cnps', models.BooleanField(default=True, verbose_name='Soumis à la CNPS')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='paie.bulletinpaie', verbose_name='Bulletin')),
                ('prime_configuree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='paie.primeconfiguree', verbose_name='Prime du catalogue (optionnel)')),
            ],
            options={
                'verbose_name': 'Prime / indemnité',
                'verbose_name_plural': 'Primes / indemnités',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employe',
            unique_together={('employeur', 'matricule')},
        ),
        migrations.CreateModel(
            name='CategorieSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Catégorie')),
                ('salaire_minimum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire minimum catégoriel (FCFA)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grille', to='paie.secteuractivite', verbose_name='Secteur')),
            ],
            options={
                'verbose_name': 'Catégorie de salaire',
                'verbose_name_plural': 'Grille des salaires',
                'ordering': ['secteur', 'ordre'],
                'unique_together': {('secteur', 'code')},
            },
        ),
    ]
