# Generated by Django 6.0.6 on 2026-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='sursalaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sursalaire'),
        ),
    ]
