# Generated by Django 6.0.6 on 2026-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_bulletinpaie_sursalaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprime',
            name='plafond_exoneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Plafond d'exonération (FCFA)"),
        ),
        migrations.AddField(
            model_name='primeconfiguree',
            name='plafond_exoneration',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Utilisé uniquement si la nature fiscale est « Exonéré jusqu'à un plafond ». Ex : transport 30 000.", max_digits=12, verbose_name="Plafond d'exonération (FCFA)"),
        ),
        migrations.AlterField(
            model_name='ligneprime',
            name='traitement_fiscal',
            field=models.CharField(choices=[('exonere', 'Exonéré (ni impôt ni cotisation)'), ('imposable', 'Imposable / cotisable à 100%'), ('abattement', 'Imposable après abattement de 10%'), ('plafonne', "Exonéré jusqu'à un plafond, imposable au-delà")], default='imposable', max_length=12, verbose_name='Traitement fiscal (ITS)'),
        ),
        migrations.AlterField(
            model_name='primeconfiguree',
            name='traitement_fiscal',
            field=models.CharField(choices=[('exonere', 'Exonéré (ni impôt ni cotisation)'), ('imposable', 'Imposable / cotisable à 100%'), ('abattement', 'Imposable après abattement de 10%'), ('plafonne', "Exonéré jusqu'à un plafond, imposable au-delà")], default='imposable', max_length=12, verbose_name='Nature fiscale'),
        ),
    ]
