# Generated by Django 6.0.6 on 2026-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_ligneprime_plafond_exoneration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sursalaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sursalaire (complément au salaire catégoriel, FCFA)'),
        ),
    ]
