# Generated by Django 6.0.6 on 2026-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_employe_sursalaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprime',
            name='type_rubrique',
            field=models.CharField(choices=[('GAIN', 'Gain (prime / indemnité)'), ('RETENUE', 'Retenue')], default='GAIN', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='primeconfiguree',
            name='type_rubrique',
            field=models.CharField(choices=[('GAIN', 'Gain (prime / indemnité)'), ('RETENUE', 'Retenue')], default='GAIN', max_length=10, verbose_name='Type'),
        ),
    ]
