# Generated by Django 6.0.6 on 2026-07-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_ligneprime_type_rubrique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriqueRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_recurrentes', to='paie.employe', verbose_name='Salarié')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paie.primeconfiguree', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Rubrique récurrente du salarié',
                'verbose_name_plural': 'Rubriques récurrentes des salariés',
            },
        ),
    ]
