# Generated by Django 6.0.6 on 2026-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_rubriquerecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='cmu_conjoint_a_charge',
            field=models.BooleanField(default=False, verbose_name='Conjoint à charge pour la CMU (conjoint sans emploi)'),
        ),
        migrations.AddField(
            model_name='employe',
            name='cmu_enfants_a_charge',
            field=models.BooleanField(default=True, verbose_name='Enfants à charge pour la CMU (décocher si le conjoint les couvre)'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_employeurs/', verbose_name="Logo de l'entreprise"),
        ),
    ]
