# Generated by Django 6.0.6 on 2026-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0007_employe_cmu_conjoint_a_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrepaie',
            name='taux_fdfp_fpc',
        ),
        migrations.AddField(
            model_name='parametrepaie',
            name='taux_ce_expatrie',
            field=models.DecimalField(decimal_places=2, default=9.2, max_digits=5, verbose_name='Contribution employeur — expatrié (%)'),
        ),
        migrations.AddField(
            model_name='parametrepaie',
            name='taux_ce_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Contribution employeur — local (%)'),
        ),
        migrations.AddField(
            model_name='parametrepaie',
            name='taux_cn',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='Contribution nationale (%)'),
        ),
    ]
