# Generated by Django 6.0.6 on 2026-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0008_remove_parametrepaie_taux_fdfp_fpc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrepaie',
            name='taux_fdfp_fpc',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=5, verbose_name='FDFP Formation Prof. Continue (%)'),
        ),
    ]
