# Generated by Django 6.0.6 on 2026-07-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0009_parametrepaie_taux_fdfp_fpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='est_solde_tout_compte',
            field=models.BooleanField(default=False, verbose_name='Solde de tout compte'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='motif_sortie',
            field=models.CharField(blank=True, max_length=60, verbose_name='Motif de sortie'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_precarite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prime de précarité (fin de CDD)'),
        ),
    ]
