# Generated by Django 6.0.6 on 2026-07-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0010_bulletinpaie_est_solde_tout_compte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code emploi')),
                ('libelle', models.CharField(max_length=100, verbose_name="Libellé de l'emploi")),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Emploi',
                'verbose_name_plural': 'Emplois',
                'ordering': ['ordre', 'code'],
            },
        ),
    ]
