# Generated by Django 6.0.6 on 2026-07-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0011_emploi'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='emploi_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paie.emploi', verbose_name='Emploi (liste)'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('journalier', 'Journalier'), ('ponctuel', 'Ponctuel')], default='mensuel', max_length=15, verbose_name='Mode de paiement'),
        ),
    ]
