# Generated by Django 6.0.6 on 2026-07-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0012_employe_emploi_ref_alter_employe_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='motif_sortie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Motif de sortie'),
        ),
        migrations.CreateModel(
            name='PeriodeEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, verbose_name='Matricule utilisé sur cette période')),
                ('contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage')], max_length=10, verbose_name='Type de contrat')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('motif_sortie', models.CharField(blank=True, max_length=100, verbose_name='Motif de sortie')),
                ('date_cloture', models.DateTimeField(auto_now_add=True, verbose_name='Clôturée le')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_anterieures', to='paie.employe', verbose_name='Salarié')),
            ],
            options={
                'verbose_name': "Période d'emploi antérieure",
                'verbose_name_plural': "Périodes d'emploi antérieures",
                'ordering': ['-date_sortie'],
            },
        ),
    ]
