# Generated by Django 6.0.6 on 2026-07-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0013_employe_motif_sortie_periodeemploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglageGenerationAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Génération automatique activée')),
                ('jour_du_mois', models.IntegerField(default=28, help_text='Ex. 28. Utilise 31 pour « dernier jour du mois ».', verbose_name='Jour du mois pour générer')),
                ('derniere_execution', models.DateField(blank=True, null=True, verbose_name='Dernière génération effectuée')),
                ('employeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglage_generation', to='paie.employeur', verbose_name='Employeur')),
            ],
            options={
                'verbose_name': 'Réglage de génération automatique',
                'verbose_name_plural': 'Réglages de génération automatique',
            },
        ),
    ]
