# Generated by Django 6.0.6 on 2026-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0014_reglagegenerationauto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='hsup_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup à 100%'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='hsup_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup à 15%'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='hsup_50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup à 50%'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='hsup_75',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup à 75%'),
        ),
    ]
