# Generated by Django 6.0.6 on 2026-07-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0015_bulletinpaie_hsup_100_bulletinpaie_hsup_15_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationDASC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Exercice')),
                ('cotisations_t1', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cotisations déclarées 1T')),
                ('cotisations_t2', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cotisations déclarées 2T')),
                ('cotisations_t3', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cotisations déclarées 3T')),
                ('cotisations_t4', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cotisations déclarées 4T')),
                ('paiements_t1', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Paiements effectués 1T')),
                ('paiements_t2', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Paiements effectués 2T')),
                ('paiements_t3', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Paiements effectués 3T')),
                ('paiements_t4', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Paiements effectués 4T')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_dasc', to='paie.employeur')),
            ],
            options={
                'verbose_name': 'Déclaration DASC',
                'verbose_name_plural': 'Déclarations DASC',
                'unique_together': {('employeur', 'annee')},
            },
        ),
    ]
