# Generated by Django 6.0.6 on 2026-07-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0016_declarationdasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglementCNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Exercice')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date du paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence du paiement')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_cnps', to='paie.employeur')),
            ],
            options={
                'verbose_name': 'Règlement CNPS',
                'verbose_name_plural': 'Règlements CNPS',
                'ordering': ['annee', 'mois'],
                'unique_together': {('employeur', 'annee', 'mois')},
            },
        ),
    ]
