# Generated by Django 6.0.6 on 2026-07-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0017_reglementcnps'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='decaissement_pret',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Décaissement de prêt (gain non imposable)'),
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant emprunté')),
                ('mensualite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mensualité')),
                ('date_debut', models.DateField(verbose_name='Date de début (1er remboursement)')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('decaisse', models.BooleanField(default=False, verbose_name='Décaissement effectué (versé au salarié)')),
                ('solde', models.BooleanField(default=False, verbose_name='Prêt soldé')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='paie.employe')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='paie.pret')),
            ],
            options={
                'ordering': ['annee', 'mois'],
                'unique_together': {('pret', 'mois', 'annee')},
            },
        ),
    ]
