# Generated by Django 6.0.6 on 2026-07-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0018_bulletinpaie_decaissement_pret_pret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(max_length=50, verbose_name='Type de document')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('cle', models.CharField(db_index=True, max_length=200, verbose_name="Clé d'unicité")),
                ('contenu', models.BinaryField(verbose_name='Contenu du fichier')),
                ('nom_fichier', models.CharField(max_length=200, verbose_name='Nom du fichier')),
                ('content_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Type MIME')),
                ('mois', models.IntegerField(blank=True, null=True, verbose_name='Mois')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='Année (exercice)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('annee_creation', models.IntegerField(verbose_name='Année civile de création')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_archives', to='paie.employe')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_archives', to='paie.employeur')),
            ],
            options={
                'verbose_name': 'Document archivé',
                'verbose_name_plural': 'Documents archivés',
                'ordering': ['-cree_le'],
            },
        ),
    ]
