# Generated by Django 6.0.6 on 2026-07-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0019_documentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='conge_date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début du congé'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='conge_date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin du congé'),
        ),
    ]
