# Generated by Django 6.0.6 on 2026-07-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0020_bulletinpaie_conge_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='cle_rib',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Clé RIB'),
        ),
        migrations.AddField(
            model_name='banque',
            name='code_banque',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code banque'),
        ),
        migrations.AddField(
            model_name='banque',
            name='code_guichet',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code guichet (agence)'),
        ),
        migrations.AddField(
            model_name='banque',
            name='est_principal',
            field=models.BooleanField(default=False, verbose_name='Compte principal (émetteur des virements)'),
        ),
        migrations.AddField(
            model_name='banque',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='banque',
            name='intitule_compte',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Intitulé du compte'),
        ),
        migrations.AddField(
            model_name='banque',
            name='numero_compte',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='couleur_documents',
            field=models.CharField(blank=True, default='#e91e63', help_text='Code hexadécimal, ex. #e91e63 (rose K&L) ou #2e7d32 (vert).', max_length=7, verbose_name='Couleur des documents de paie'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='date_debut_premier_exercice',
            field=models.DateField(blank=True, help_text="Début d'activité, ou début de reprise si le client est repris, ou année de la lettre de mission par défaut.", null=True, verbose_name='Date de début du premier exercice'),
        ),
    ]
