# Generated by Django 6.0.6 on 2026-07-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0021_banque_cle_rib_banque_code_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='banque_cle_rib',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Clé RIB'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code banque'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_guichet',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code guichet (agence)'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_iban',
            field=models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_intitule',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Intitulé du compte (titulaire)'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='employeur',
            name='banque_numero_compte',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro de compte'),
        ),
    ]
