# Generated by Django 6.0.6 on 2026-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0022_employeur_banque_cle_rib_employeur_banque_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='banque_cle_rib',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Clé RIB'),
        ),
        migrations.AddField(
            model_name='employe',
            name='banque_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code banque'),
        ),
        migrations.AddField(
            model_name='employe',
            name='banque_guichet',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code guichet (agence)'),
        ),
        migrations.AddField(
            model_name='employe',
            name='banque_iban',
            field=models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], default='especes', max_length=15, verbose_name='Mode de paiement'),
        ),
    ]
