# Generated by Django 6.0.6 on 2026-07-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0023_employe_banque_cle_rib_employe_banque_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel (décompté du compteur)'), ('exceptionnel', 'Congé exceptionnel (mariage, décès, naissance…)')], default='annuel', max_length=15, verbose_name='Type de congé')),
                ('date_depart', models.DateField(verbose_name='Date de départ en congé')),
                ('date_retour', models.DateField(verbose_name='Date de retour (reprise du travail)')),
                ('jours_ouvrables', models.IntegerField(default=0, verbose_name='Jours ouvrables de congé')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemnité totale de congé (FCFA)')),
                ('motif', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif (facultatif)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='paie.employe', verbose_name='Salarié')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_depart'],
            },
        ),
    ]
