# Generated by Django 6.0.6 on 2026-07-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0024_alter_documentarchive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date du jour férié')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
    ]
