# Generated by Django 6.0.6 on 2026-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0027_reconstruire_jourferie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='lieu_travail',
            field=models.CharField(blank=True, help_text="Laisser vide pour utiliser l'adresse de l'entreprise par défaut.", max_length=200, verbose_name="Lieu d'exécution du contrat"),
        ),
    ]
