# Generated by Django 6.0.6 on 2026-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0028_employe_lieu_travail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.CharField(blank=True, help_text='Intitulé du poste réellement occupé (ex. Comptable, Chauffeur) — distinct du code emploi réglementaire.', max_length=150, verbose_name='Poste occupé'),
        ),
    ]
