# Generated by Django 6.0.6 on 2026-07-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0029_employe_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('embauche', 'Embauche'), ('transformation_cdi', 'Transformation CDD → CDI'), ('sortie', 'Sortie / fin de contrat'), ('reembauche', 'Réembauche')], max_length=20, verbose_name='Type de mouvement')),
                ('date_mouvement', models.DateField(verbose_name='Date du mouvement')),
                ('detail', models.CharField(blank=True, default='', max_length=250, verbose_name='Détail')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='paie.employe', verbose_name='Salarié')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_personnel', to='paie.employeur', verbose_name='Employeur')),
            ],
            options={
                'verbose_name': 'Mouvement du personnel',
                'verbose_name_plural': 'Mouvements du personnel',
                'ordering': ['-date_mouvement', '-cree_le'],
            },
        ),
    ]
