# Generated by Django 6.0.6 on 2026-07-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0030_mouvementpersonnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.CharField(choices=[('maladie', 'Maladie justifiée (salaire maintenu)'), ('injustifiee', 'Absence injustifiée (salaire réduit)'), ('autorisee_non_payee', 'Absence autorisée non payée (salaire réduit)'), ('autre', 'Autre motif')], default='maladie', max_length=25, verbose_name='Motif')),
                ('justificatif', models.CharField(blank=True, default='', max_length=200, verbose_name='Référence du justificatif (facultatif)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='paie.employe', verbose_name='Salarié')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
    ]
