# Generated by Django 6.0.6 on 2026-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0031_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='cmu_salarie_historique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CMU salarié historique (figé)'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cnps_salarie_historique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CNPS salarié historique (figé)'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='est_historique',
            field=models.BooleanField(default=False, verbose_name='Bulletin historique (repris, montants figés)'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='its_historique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ITS historique (figé)'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='net_historique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Net payé historique (figé)'),
        ),
    ]
