# Generated by Django 6.0.6 on 2026-07-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0032_bulletinpaie_cmu_salarie_historique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrepaie',
            name='taux_fdfp_fpc',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='FDFP Formation Prof. Continue (%)'),
        ),
    ]
