# Generated by Django 6.0.6 on 2026-07-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0033_alter_parametrepaie_taux_fdfp_fpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='retire_jours',
            field=models.BooleanField(default=True, help_text="Décoche si l'absence ne doit pas réduire le salaire, malgré le motif.", verbose_name='Retirer les jours du bulletin (impact salaire)'),
        ),
    ]
