# Generated by Django 6.0.6 on 2026-07-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0034_absence_retire_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='duree_essai_mois',
            field=models.IntegerField(blank=True, help_text='Renseignée automatiquement lors de la génération du contrat.', null=True, verbose_name="Durée de la période d'essai (mois)"),
        ),
    ]
