# Generated by Django 6.0.6 on 2026-07-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0035_employe_duree_essai_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpersonnel',
            name='type_mouvement',
            field=models.CharField(choices=[('embauche', 'Embauche'), ('transformation_cdi', 'Transformation CDD → CDI'), ('sortie', 'Sortie / fin de contrat'), ('reembauche', 'Réembauche'), ('changement_salaire', 'Changement de salaire'), ('changement_poste', 'Changement de poste')], max_length=20, verbose_name='Type de mouvement'),
        ),
    ]
