# Generated by Django 6.0.6 on 2026-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lettre_mission_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lettres_mission/', verbose_name='Lettre de mission (PDF généré)'),
        ),
    ]
