# Generated by Django 6.0.6 on 2026-06-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('devis', '0002_devis_lettre_mission_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client_rattache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_supplementaires', to='clients.client', verbose_name='Client rattaché (si client existant)'),
        ),
    ]
