# Generated by Django 6.0.6 on 2026-06-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_devis_client_rattache'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
