# Generated by Django 6.0.6 on 2026-06-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_devis_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='note_explicative',
            field=models.TextField(blank=True, verbose_name='Note explicative (générée par IA)'),
        ),
    ]
