# Generated by Django 6.0.6 on 2026-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_devis_note_explicative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='note_explicative',
            field=models.JSONField(blank=True, null=True, verbose_name='Note explicative (générée par IA)'),
        ),
    ]
