# Generated by Django 6.0.6 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_alter_devis_note_explicative'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_effet_mission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'effet de la mission"),
        ),
        migrations.AddField(
            model_name='devis',
            name='duree_mission_mois',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='Durée de la mission (mois)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='exercice_concerne',
            field=models.CharField(blank=True, help_text='Ex : 2026', max_length=9, verbose_name='Exercice comptable concerné'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lieu_signature',
            field=models.CharField(blank=True, default='Abidjan', max_length=100, verbose_name='Lieu de signature'),
        ),
        migrations.AddField(
            model_name='devis',
            name='modalites_paiement',
            field=models.CharField(blank=True, help_text='Ex : mensuels payables le 5 de chaque mois', max_length=255, verbose_name='Modalités de paiement des honoraires'),
        ),
        migrations.AddField(
            model_name='devis',
            name='regime_mission',
            field=models.CharField(choices=[('RECURRENTE', 'Mission récurrente (suivi régulier)'), ('PONCTUELLE', 'Mission ponctuelle (prestation unique)')], default='RECURRENTE', max_length=12, verbose_name='Régime de la mission'),
        ),
    ]
