# Generated by Django 6.0.6 on 2026-06-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_devis_date_effet_mission_devis_duree_mission_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='ca_annee_precedente',
            field=models.CharField(blank=True, max_length=50, verbose_name="Chiffre d'affaires de l'année précédente"),
        ),
        migrations.AddField(
            model_name='devis',
            name='code_cdi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code CDI'),
        ),
        migrations.AddField(
            model_name='devis',
            name='declaration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la déclaration'),
        ),
        migrations.AddField(
            model_name='devis',
            name='declaration_lieu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Déclaration faite à'),
        ),
        migrations.AddField(
            model_name='devis',
            name='exoneration_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Exonération — début'),
        ),
        migrations.AddField(
            model_name='devis',
            name='exoneration_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Exonération — fin'),
        ),
        migrations.AddField(
            model_name='devis',
            name='exoneration_fondement',
            field=models.CharField(blank=True, help_text='Code des Investissements, Code minier, Code pétrolier, Régime franc, Autres…', max_length=200, verbose_name="Fondement de l'exonération"),
        ),
        migrations.AddField(
            model_name='devis',
            name='exoneration_type',
            field=models.CharField(blank=True, choices=[('AUCUNE', 'Aucune'), ('TOTALE', 'Exonération totale'), ('PARTIELLE', 'Exonération partielle')], default='AUCUNE', max_length=10, verbose_name="Type d'exonération"),
        ),
        migrations.AddField(
            model_name='devis',
            name='proprietaire_adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Propriétaire du local — Adresse'),
        ),
        migrations.AddField(
            model_name='devis',
            name='proprietaire_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Propriétaire du local — Email'),
        ),
        migrations.AddField(
            model_name='devis',
            name='proprietaire_ncc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Propriétaire du local — NCC'),
        ),
        migrations.AddField(
            model_name='devis',
            name='proprietaire_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Propriétaire du local — Nom / Raison sociale'),
        ),
        migrations.AddField(
            model_name='devis',
            name='proprietaire_tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='Propriétaire du local — Téléphone'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signataire_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du signataire de la déclaration'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signataire_qualite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qualité du signataire'),
        ),
    ]
