# Generated by Django 6.0.6 on 2026-06-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_devis_ca_annee_precedente_devis_code_cdi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom et prénoms ou raison sociale')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('part_montant', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant de la part (FCFA)')),
                ('part_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Part (%)')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associes', to='devis.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Associé / Actionnaire',
                'verbose_name_plural': 'Associés / Actionnaires',
                'ordering': ['-part_pourcentage'],
            },
        ),
    ]
