# Generated by Django 6.0.6 on 2026-06-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0009_associe'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='nombre_salaries',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Sert à déterminer les tranches de prix (paie, CNPS)', null=True, verbose_name='Nombre de salariés'),
        ),
    ]
