# Generated by Django 6.0.6 on 2026-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0011_alter_devis_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_derniere_relance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la dernière relance'),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi au prospect"),
        ),
        migrations.AddField(
            model_name='devis',
            name='nombre_relances',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de relances effectuées'),
        ),
    ]
