# Generated by Django 6.0.6 on 2026-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0012_devis_date_derniere_relance_devis_date_envoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='type_client',
            field=models.CharField(choices=[('PP_INFORMEL', 'Personne Physique — secteur informel'), ('PP_CONSTITUEE', 'Personne Physique légalement constituée'), ('PM', 'Personne Morale')], default='PM', max_length=20, verbose_name='Type de client'),
        ),
    ]
