# Generated by Django 6.0.6 on 2026-06-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0013_alter_devis_type_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numéro')),
                ('client_nom', models.CharField(max_length=255, verbose_name='Client')),
                ('client_ncc', models.CharField(blank=True, max_length=30, verbose_name='NCC client')),
                ('type_facturation', models.CharField(choices=[('PONCTUELLE', 'Ponctuelle'), ('RECURRENTE', 'Récurrente')], default='PONCTUELLE', max_length=20)),
                ('frequence', models.CharField(blank=True, choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], help_text='Uniquement si la facturation est récurrente', max_length=20)),
                ('date_signature', models.DateField(blank=True, help_text="Déclencheur de la facturation (saisi manuellement pour l'instant)", null=True, verbose_name='Date de signature de la lettre')),
                ('montant_ht', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('A_CERTIFIER', 'À certifier'), ('CERTIFIEE', 'Certifiée DGI'), ('ENVOYEE', 'Envoyée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('fne_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence FNE')),
                ('fne_token', models.CharField(blank=True, max_length=255, verbose_name='Token FNE (QR code)')),
                ('fne_sticker', models.CharField(blank=True, max_length=100, verbose_name='Sticker FNE')),
                ('devis_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='devis.devis', verbose_name='Lettre de mission / devis source')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
