# Generated by Django 6.0.6 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0014_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé au prospect'), ('VALIDE', 'Validé (client intégré)')], default='BROUILLON', max_length=15, verbose_name='Statut du devis'),
        ),
    ]
