# Generated by Django 6.0.6 on 2026-07-17 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0015_alter_devis_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lettre_motif_refus',
            field=models.TextField(blank=True, help_text='Rempli par la Direction si le dossier est renvoyé au secrétariat pour correction.', verbose_name='Motif du refus / des corrections demandées'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_signee_client_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signée par le client le'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_soumise_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumise à la Direction le'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_soumise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_soumis_direction', to=settings.AUTH_USER_MODEL, verbose_name='Soumise par (secrétariat)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_statut',
            field=models.CharField(choices=[('BROUILLON', "Brouillon (Porte d'entrée en cours)"), ('EN_VALIDATION_DIRECTION', 'En attente de validation Direction'), ('VALIDEE_DIRECTION', 'Validée et signée par la Direction'), ('ENVOYEE_CLIENT', 'Envoyée au client'), ('SIGNEE_CLIENT', 'Signée par le client')], default='BROUILLON', max_length=25, verbose_name='Statut de la lettre de mission'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_validee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validée et signée (Direction) le'),
        ),
        migrations.AddField(
            model_name='devis',
            name='lettre_validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_valides_direction', to=settings.AUTH_USER_MODEL, verbose_name='Validée par (Direction)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='modules_concernes',
            field=models.JSONField(blank=True, default=list, help_text='Modules métier qui interviendront sur ce dossier tout au long de la mission.', verbose_name='Modules concernés par ce dossier'),
        ),
        migrations.CreateModel(
            name='DocumentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('RCCM', 'RCCM'), ('DFE', "DFE — Déclaration Fiscale d'Existence"), ('STATUTS', 'Statuts de la société'), ('INSPECTION_TRAVAIL', "Déclaration à l'Inspection du Travail"), ('CNPS', "Notification d'immatriculation CNPS"), ('PIECE_GERANT', "Pièce d'identité du gérant / dirigeant"), ('CONTRAT_BAIL', 'Contrat de bail'), ('AUTRE', 'Autre document comptable ou administratif')], max_length=20, verbose_name='Type de document')),
                ('libelle_libre', models.CharField(blank=True, help_text="Uniquement utilisé pour le type 'Autre document comptable ou administratif'", max_length=200, verbose_name='Libellé (si Autre)')),
                ('statut', models.CharField(choices=[('A_EXAMINER', 'À examiner'), ('FOURNI', 'Fourni'), ('ABSENT_CLIENT', "Absent — le client ne l'a pas"), ('ABSENT_A_FAIRE', "Absent — le cabinet doit l'établir (facturable)")], default='A_EXAMINER', max_length=15, verbose_name='Statut')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/porte_entree/', verbose_name='Fichier')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('ligne_facturable_ajoutee', models.BooleanField(default=False, help_text="Coché automatiquement dès qu'une ligne de prestation a été ajoutée au devis pour ce document manquant.", verbose_name='Ligne de prestation ajoutée pour ce document')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='devis.devis', verbose_name='Devis / dossier')),
            ],
            options={
                'verbose_name': 'Pièce du dossier',
                'verbose_name_plural': 'Pièces du dossier',
                'ordering': ['type_document'],
            },
        ),
    ]
