# Generated by Django 6.0.6 on 2026-07-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0016_devis_lettre_motif_refus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='centre_impots',
            field=models.CharField(blank=True, help_text='Utile pour la Comptabilité/Fiscalité et pour la Paie (fiche Employeur)', max_length=150, verbose_name='Centre des impôts'),
        ),
        migrations.AddField(
            model_name='devis',
            name='numero_cnps',
            field=models.CharField(blank=True, help_text="Numéro d'immatriculation employeur à la CNPS — nécessaire dès que 'Qualité d'employeur' est coché, utilisé par le module Paie/RH", max_length=30, verbose_name='N° employeur CNPS'),
        ),
        migrations.AlterField(
            model_name='documentpiece',
            name='statut',
            field=models.CharField(choices=[('IGNORE', 'Ignoré'), ('FOURNI', 'Fourni'), ('ABSENT', 'Absent — à établir par le cabinet (facturable)')], default='IGNORE', max_length=15, verbose_name='Statut'),
        ),
    ]
