# Generated by Django 6.0.6 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0017_devis_centre_impots_devis_numero_cnps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lettre_signataire_client',
            field=models.CharField(blank=True, help_text='Nom de la personne ayant signé la lettre de mission côté client.', max_length=200, verbose_name='Signataire client'),
        ),
    ]
