# Generated by Django 6.0.6 on 2026-07-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0018_devis_lettre_signataire_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation de la ligne')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire HT')),
                ('taux_tva', models.CharField(choices=[('18', 'TVA 18% (taux normal)'), ('9', 'TVA 9% (taux réduit)'), ('0', 'Exonéré (0%)')], default='18', max_length=2, verbose_name='Taux de TVA')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de factures',
            },
        ),
    ]
