# Generated by Django 6.0.6 on 2026-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0019_lignefacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='jour_emission_facture',
            field=models.PositiveSmallIntegerField(default=5, help_text='Jour du mois où les factures récurrentes de cette mission sont générées automatiquement (plafonné les mois courts).', verbose_name="Jour d'émission des factures récurrentes"),
        ),
        migrations.AddField(
            model_name='facture',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email client (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone client (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='devise_etrangere',
            field=models.CharField(blank=True, choices=[('', 'Aucune (facturation en FCFA / XOF)'), ('XOF', 'Franc CFA (XOF)'), ('USD', 'Dollar Américain (USD)'), ('EUR', 'Euro (EUR)'), ('JPY', 'Yen Japonais (JPY)'), ('CAD', 'Dollar Canadien (CAD)'), ('GBP', 'Livre Sterling Britannique (GBP)'), ('AUD', 'Dollar Australien (AUD)'), ('CNH', 'Yuan Chinois (CNH)'), ('CHF', 'Franc Suisse (CHF)'), ('HKD', 'Dollar Hong Kong (HKD)'), ('NZD', 'Dollar Néo-Zélandais (NZD)')], max_length=3, verbose_name='Devise étrangère'),
        ),
        migrations.AddField(
            model_name='facture',
            name='etablissement',
            field=models.CharField(blank=True, max_length=150, verbose_name='Établissement (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_balance_sticker',
            field=models.IntegerField(blank=True, null=True, verbose_name='Solde de stickers restants (retour FNE)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_date_certification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certifiée le'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_erreur',
            field=models.TextField(blank=True, verbose_name='Dernière erreur de certification'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_invoice_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID interne FNE (nécessaire pour un avoir)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_ncc_emetteur',
            field=models.CharField(blank=True, max_length=20, verbose_name='NCC émetteur (retour FNE)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_statut',
            field=models.CharField(choices=[('NON_CERTIFIEE', 'Non certifiée'), ('CERTIFIEE', 'Certifiée'), ('ERREUR', 'Erreur de certification')], default='NON_CERTIFIEE', max_length=15, verbose_name='Statut FNE'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_warning',
            field=models.BooleanField(default=False, verbose_name='Alerte stock sticker (retour FNE)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='invoice_type',
            field=models.CharField(choices=[('sale', 'Vente')], default='sale', max_length=10, verbose_name='Type FNE'),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_rne',
            field=models.BooleanField(default=False, verbose_name='Facture liée à un reçu (RNE) ? (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='message_commercial',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message commercial'),
        ),
        migrations.AddField(
            model_name='facture',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('mobile-money', 'Mobile Money'), ('transfer', 'Virement bancaire'), ('deferred', 'À terme')], max_length=15, verbose_name='Méthode de paiement (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='pied_de_page',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message de bas de facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='point_de_vente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Point de vente (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise_montant',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Reportée depuis la remise du devis d'origine au moment de la génération", max_digits=12, verbose_name='Remise (montant FCFA)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='rne_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro du reçu — RNE (O si liée à un reçu)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_devise_etrangere',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Taux de la devise étrangère (O si devise étrangère renseignée)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='template',
            field=models.CharField(blank=True, choices=[('B2B', 'Entreprise / professionnel (avec NCC)'), ('B2F', "Client à l'international"), ('B2G', 'Institution gouvernementale'), ('B2C', 'Particulier')], max_length=3, verbose_name='Modèle de facturation FNE (O)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='vendeur_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du vendeur (facultatif)'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence article'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='unite_mesure',
            field=models.CharField(blank=True, help_text='Ex : mois, forfait, heure', max_length=30, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation'),
        ),
    ]
