# Generated by Django 6.0.6 on 2026-07-20 15:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0020_devis_jour_emission_facture_facture_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, help_text="Calculée automatiquement à l'émission (voir save()), modifiable au cas par cas.", null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise (FNE)'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('CONTESTEE', 'Contestée'), ('EN_LITIGE', 'En litige'), ('CORRIGEE', 'Corrigée'), ('EN_RETARD', 'En retard'), ('EN_CONTENTIEUX', 'En contentieux'), ('IRRECOUVRABLE', 'Irrécouvrable'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoriqueStatutFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=25)),
                ('nouveau_statut', models.CharField(max_length=25)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='devis.facture')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut (facture)',
                'verbose_name_plural': 'Historiques de statuts (factures)',
                'ordering': ['date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('date_paiement', models.DateField(default=datetime.date.today, verbose_name='Date du paiement')),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15)),
                ('banque', models.CharField(blank=True, max_length=100, verbose_name='Banque / établissement')),
                ('reference_bancaire', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='paiements/justificatifs/', verbose_name='Justificatif')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='devis.facture')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['date_paiement'],
            },
        ),
    ]
