# Generated by Django 6.0.6 on 2026-07-20 15:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0021_facture_date_echeance_alter_facture_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_avoir', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('type_avoir', models.CharField(choices=[('CORRECTION', "Correction d'erreur de facturation"), ('GESTE_COMMERCIAL', 'Geste commercial'), ('ANNULATION_PARTIELLE', 'Annulation partielle de prestation'), ('RESOLUTION_LITIGE', 'Résolution de litige')], max_length=25)),
                ('motif', models.TextField(verbose_name='Motif')),
                ('certifie_fne', models.BooleanField(default=False, verbose_name='Certifié FNE')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='devis.facture')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensations_recues', to='devis.facture', verbose_name='Facture soldée')),
                ('facture_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensations_emises', to='devis.facture', verbose_name='Facture en trop-perçu')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compensation',
                'verbose_name_plural': 'Compensations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('date_remboursement', models.DateField(default=datetime.date.today)),
                ('mode_remboursement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='remboursements/justificatifs/')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='devis.facture')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_remboursement'],
            },
        ),
    ]
