# Generated by Django 6.0.6 on 2026-07-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0022_avoir_compensation_remboursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeRelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'étape")),
                ('delai_jours', models.PositiveIntegerField(help_text="Jours après la date d'échéance", verbose_name='Déclenchement à J+')),
                ('type_action', models.CharField(choices=[('EMAIL_COURTOIS', 'Email courtois'), ('EMAIL_FERME', 'Email plus ferme'), ('NOTIFICATION_INTERNE', 'Notification interne'), ('LETTRE_PDF', 'Lettre PDF'), ('ESCALADE_DIRECTION', 'Escalade Direction'), ('ALERTE_CONTENTIEUX', 'Alerte contentieux (décision Direction requise)')], max_length=25)),
                ('sujet_email', models.CharField(blank=True, max_length=200, verbose_name='Sujet (si email)')),
                ('corps_message', models.TextField(blank=True, help_text='Variables disponibles : {client_nom}, {numero_facture}, {montant_du}, {jours_retard}', verbose_name='Corps du message')),
                ('actif', models.BooleanField(default=True, verbose_name='Étape active')),
            ],
            options={
                'verbose_name': 'Étape de relance',
                'verbose_name_plural': 'Étapes de relance',
                'ordering': ['delai_jours'],
            },
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('reussie', models.BooleanField(default=True)),
                ('erreur', models.TextField(blank=True)),
                ('document_genere', models.FileField(blank=True, null=True, upload_to='relances/lettres/')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relances_declenchees', to='devis.etaperelance')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='devis.facture')),
            ],
            options={
                'verbose_name': 'Relance déclenchée',
                'verbose_name_plural': 'Relances déclenchées',
                'ordering': ['-date_declenchement'],
                'unique_together': {('facture', 'etape')},
            },
        ),
    ]
