# Generated by Django 6.0.6 on 2026-07-20 17:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0023_etaperelance_relance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('ncc', models.CharField(blank=True, max_length=20, verbose_name='NCC')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('delai_paiement_jours', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Délai de paiement négocié (jours)')),
                ('notation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Notation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='recouvreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portefeuille_creances', to=settings.AUTH_USER_MODEL, verbose_name='Recouvreur affecté'),
        ),
        migrations.CreateModel(
            name='ActionRecouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('EMAIL', 'Email envoyé'), ('VISITE', 'Visite / rendez-vous'), ('AUTRE', 'Autre action')], max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_recouvrement', to='devis.facture')),
                ('recouvreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action de recouvrement',
                'verbose_name_plural': 'Actions de recouvrement',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='devis.categoriedepense', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_depense', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant_ht', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant HT')),
                ('taux_tva', models.CharField(choices=[('18', 'TVA 18% (taux normal)'), ('9', 'TVA 9% (taux réduit)'), ('0', 'Exonéré (0%)')], default='18', max_length=2, verbose_name='Taux de TVA')),
                ('date_facture', models.DateField(verbose_name='Date de la facture fournisseur')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15)),
                ('compte_bancaire', models.CharField(blank=True, max_length=100, verbose_name='Compte bancaire')),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PROGRAMME', 'Programmé'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='A_PAYER', max_length=25)),
                ('est_recurrente', models.BooleanField(default=False, verbose_name='Dépense récurrente')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='devis.categoriedepense')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='devis.fournisseur')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('FACTURE', 'Facture PDF'), ('RECU', 'Reçu'), ('PHOTO', 'Photo'), ('DEVIS', 'Devis'), ('BON_COMMANDE', 'Bon de commande')], max_length=15)),
                ('fichier', models.FileField(upload_to='depenses/documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='devis.depense')),
            ],
            options={
                'verbose_name': 'Document (dépense)',
                'verbose_name_plural': 'Documents (dépenses)',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ContratFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('fichier', models.FileField(upload_to='fournisseurs/contrats/', verbose_name='Fichier')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='devis.fournisseur')),
            ],
            options={
                'verbose_name': 'Contrat fournisseur',
                'verbose_name_plural': 'Contrats fournisseurs',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=25)),
                ('nouveau_statut', models.CharField(max_length=25)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='devis.depense')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut (dépense)',
                'verbose_name_plural': 'Historiques de statuts (dépenses)',
                'ordering': ['date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_type', models.CharField(choices=[('ERREUR_FACTURE', 'Erreur de facture'), ('PRESTATION_INCOMPLETE', 'Prestation incomplète'), ('DESACCORD', 'Désaccord'), ('AUTRE', 'Autre')], max_length=25, verbose_name='Motif')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', "En cours d'instruction"), ('RESOLU', 'Résolu'), ('ABANDONNE', 'Abandonné')], default='OUVERT', max_length=15)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('resolution_commentaire', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='devis.facture')),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_ouverts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireLitige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('litige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='devis.litige')),
            ],
            options={
                'verbose_name': 'Commentaire (litige)',
                'verbose_name_plural': 'Commentaires (litiges)',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('date_paiement', models.DateField(default=datetime.date.today, verbose_name='Date du paiement')),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15)),
                ('reference_bancaire', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/paiements/')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='devis.depense')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement (dépense)',
                'verbose_name_plural': 'Paiements (dépenses)',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeLitige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('fichier', models.FileField(upload_to='litiges/pieces/', verbose_name='Fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('litige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='devis.litige')),
            ],
            options={
                'verbose_name': 'Pièce jointe (litige)',
                'verbose_name_plural': 'Pièces jointes (litiges)',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
