# Generated by Django 6.0.6 on 2026-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0024_fournisseur_facture_recouvreur_actionrecouvrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='operateur_mobile_money',
            field=models.CharField(blank=True, choices=[('', '—'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Opérateur mobile money'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reconcilie_automatiquement',
            field=models.BooleanField(default=False, help_text="Toujours False tant que l'intégration API n'existe pas — sert de marqueur pour distinguer les paiements saisis à la main de ceux confirmés par webhook, une fois construit", verbose_name='Réconcilié automatiquement via API'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction_externe',
            field=models.CharField(blank=True, help_text="ID de transaction Wave/Orange Money — rempli manuellement pour l'instant, automatiquement une fois l'API branchée", max_length=100, verbose_name='Référence transaction (API opérateur)'),
        ),
        migrations.AddField(
            model_name='paiementdepense',
            name='operateur_mobile_money',
            field=models.CharField(blank=True, choices=[('', '—'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Opérateur mobile money'),
        ),
        migrations.AddField(
            model_name='paiementdepense',
            name='reconcilie_automatiquement',
            field=models.BooleanField(default=False, help_text="Toujours False tant que l'intégration API n'existe pas — sert de marqueur pour distinguer les paiements saisis à la main de ceux confirmés par webhook, une fois construit", verbose_name='Réconcilié automatiquement via API'),
        ),
        migrations.AddField(
            model_name='paiementdepense',
            name='reference_transaction_externe',
            field=models.CharField(blank=True, help_text="ID de transaction Wave/Orange Money — rempli manuellement pour l'instant, automatiquement une fois l'API branchée", max_length=100, verbose_name='Référence transaction (API opérateur)'),
        ),
    ]
