# Generated by Django 6.0.6 on 2026-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0025_facture_archive_facture_date_archivage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
