# Generated by Django 6.0.6 on 2026-07-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0026_depense_archive_depense_date_archivage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.PositiveIntegerField(verbose_name='Exercice (année)')),
                ('mois', models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour un budget annuel, ou préciser 1-12 pour un budget mensuel', null=True, verbose_name='Mois')),
                ('montant_alloue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant alloué')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='devis.categoriedepense')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-exercice', 'categorie'],
                'constraints': [models.UniqueConstraint(fields=('categorie', 'exercice', 'mois'), name='unique_budget_periode')],
            },
        ),
    ]
