# Generated by Django 6.0.6 on 2026-07-20 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0027_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilApprobation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borne_min', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='À partir de (FCFA)')),
                ('borne_max', models.DecimalField(blank=True, decimal_places=0, help_text="Laisser vide pour 'et plus'", max_digits=12, null=True, verbose_name="Jusqu'à (FCFA)")),
                ('niveau_requis', models.CharField(choices=[('CADRE', 'Chef de service (Cadre)'), ('DIRECTION', 'Direction')], max_length=15)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Seuil d'approbation",
                'verbose_name_plural': "Seuils d'approbation",
                'ordering': ['borne_min'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='niveau_requis',
            field=models.CharField(blank=True, choices=[('CADRE', 'Chef de service (Cadre)'), ('DIRECTION', 'Direction')], max_length=15),
        ),
        migrations.AddField(
            model_name='depense',
            name='soumise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='statut_validation',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise, en attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=15),
        ),
        migrations.AddField(
            model_name='depense',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriqueValidationDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('RENVOYEE_BROUILLON', 'Renvoyée en brouillon')], max_length=25)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='devis.depense')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de validation (dépense)',
                'verbose_name_plural': 'Historiques de validation (dépenses)',
                'ordering': ['date_action'],
            },
        ),
    ]
