# Generated by Django 6.0.6 on 2026-07-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0028_seuilapprobation_depense_date_soumission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='depassement_autorise',
            field=models.BooleanField(default=False, verbose_name='Dépassement budgétaire autorisé'),
        ),
        migrations.AddField(
            model_name='depense',
            name='depassement_autorise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_derogees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='motif_depassement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiquevalidationdepense',
            name='action',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('RENVOYEE_BROUILLON', 'Renvoyée en brouillon'), ('DEROGATION_BUDGET', 'Dérogation de dépassement budgétaire accordée')], max_length=25),
        ),
    ]
