# Generated by Django 6.0.6 on 2026-07-20 21:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0029_add_depense_budget_derogation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant_ht', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant HT')),
                ('taux_tva', models.CharField(choices=[('18', 'TVA 18% (taux normal)'), ('9', 'TVA 9% (taux réduit)'), ('0', 'Exonéré (0%)')], default='18', max_length=2)),
                ('frequence', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=15)),
                ('jour_generation', models.PositiveSmallIntegerField(default=1, help_text='Plafonné automatiquement les mois courts (comme jour_emission_facture sur Devis)', verbose_name='Jour du mois de génération')),
                ('mois_generation', models.PositiveSmallIntegerField(blank=True, help_text='Uniquement pour une fréquence annuelle', null=True, verbose_name='Mois de génération (si annuel)')),
                ('date_debut', models.DateField(default=datetime.date.today, verbose_name='Début de la récurrence')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin de la récurrence')),
                ('actif', models.BooleanField(default=True)),
                ('derniere_generation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_recurrentes', to='devis.categoriedepense')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_recurrentes', to='devis.fournisseur')),
            ],
            options={
                'verbose_name': 'Dépense récurrente',
                'verbose_name_plural': 'Dépenses récurrentes',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='GenerationDepenseRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_recurrente', to='devis.depense')),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='devis.depenserecurrente')),
            ],
            options={
                'ordering': ['-date_echeance'],
                'unique_together': {('recurrente', 'date_echeance')},
            },
        ),
    ]
