# Generated by Django 6.0.6 on 2026-07-20 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0030_depenserecurrente_generationdepenserecurrente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Période — début')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période — fin')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('REMBOURSEE', 'Remboursée')], default='BROUILLON', max_length=15)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('mode_remboursement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], max_length=15)),
                ('reference_remboursement', models.CharField(blank=True, max_length=100, verbose_name='Référence de remboursement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_de_frais', to=settings.AUTH_USER_MODEL)),
                ('rembourse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_de_frais_remboursees', to=settings.AUTH_USER_MODEL)),
                ('soumise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_de_frais_soumises', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_de_frais_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note de frais',
                'verbose_name_plural': 'Notes de frais',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneNoteDeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('MISSION', 'Mission'), ('TRANSPORT', 'Transport'), ('HEBERGEMENT', 'Hébergement'), ('REPAS', 'Repas'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Type de frais')),
                ('date_depense', models.DateField(verbose_name='Date de dépense')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.notedefrais')),
            ],
            options={
                'verbose_name': 'Ligne de note de frais',
                'verbose_name_plural': 'Lignes de notes de frais',
                'ordering': ['date_depense'],
            },
        ),
    ]
