# Generated by Django 6.0.6 on 2026-07-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0031_notedefrais_lignenotedefrais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromessePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_promis', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant promis')),
                ('date_promise', models.DateField(verbose_name='Date promise de paiement')),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TENUE', 'Tenue (paiement reçu à temps)'), ('ROMPUE', 'Rompue (échéance dépassée sans paiement)'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promesses', to='devis.facture')),
                ('responsable', models.ForeignKey(blank=True, help_text='Collaborateur ayant reçu la promesse (recouvreur en général)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promesses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promesse de paiement',
                'verbose_name_plural': 'Promesses de paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
