"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # charge le fichier .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-ng@qd0vg(@ud&vb*3&8qh!1gyzp1gc4d31y=06!oseh_ga8ab=")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

INTERNAL_IPS = ["127.0.0.1"]

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    "clients",
    "devis",
    "paie",
    "parametres",
    "pilotage",
    "comptes",
    "core",
    "vitrine",
    "collaborateurs",
    "portail",
    "actualites",
    "rendezvous",
    "secretariat",
    "messagerie",
    "comptabilite",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "comptes.middleware.DelaiInactiviteMiddleware",
    "portail.middleware.ParcoursAccueilMiddleware",
    "comptes.middleware_presence.PresenceMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pilotage.context_processors.navigation',
                'pilotage.context_processors.notifications_non_lues',
                'pilotage.context_processors.sous_modules_auto',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Production : PostgreSQL, configuré via la variable d'environnement DATABASE_URL
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Développement local : SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Dossier où collectstatic va rassembler tous les fichiers statiques pour la production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Fichiers uploadés (documents scannés)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# --- Configuration des Emails ---
# Le backend SMTP est configuré par défaut
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Destinataire par défaut pour les demandes de contact (Recommandation 6)
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "cabinetkl120@gmail.com")

# Expéditeur par défaut requis par la fonction send_mail de Django
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@cabinetkl.com")


# --- Authentification ---
LOGIN_URL = "login"               # où envoyer un visiteur non connecté
LOGIN_REDIRECT_URL = "aiguillage" # après connexion → carrefour qui route selon le rôle
LOGOUT_REDIRECT_URL = "/"         # où atterrir après déconnexion (accueil Vitrine)


# --- Intégrations Tierces & Outils ---
# Clé API Gemini
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Emplacement des liasses générées
DOSSIER_LIASSES_GENEREES = BASE_DIR / "liasses_generees"

# Modèles Excel pour la DGI 
# ATTENTION : Le chemin par défaut est propre à votre machine Windows locale.
# Pour la production, nous utilisons une variable d'environnement ou un fallback local.
TEMPLATES_LIASSE_DGI = {
    "NO": os.getenv("TEMPLATE_DGI_NO_PATH", str(BASE_DIR / "modeles_dgi" / "DGI-liasse-NO.xltm")),
}