# Generated by Django 6.0.6 on 2026-07-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_cgv_acceptees_client_lettre_confirmee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteSyscohada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du compte')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('classe', models.IntegerField(verbose_name='Classe (1 à 9)')),
            ],
            options={
                'verbose_name': 'Compte SYSCOHADA (plan général)',
                'verbose_name_plural': 'Plan comptable SYSCOHADA',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LigneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_liasse', models.CharField(default='NO', max_length=5, verbose_name='Régime de liasse')),
                ('code_note', models.CharField(help_text='Ex. NOTE 3A, NOTE 3C, NOTE 4', max_length=15, verbose_name='Code note')),
                ('libelle_ligne', models.CharField(max_length=200, verbose_name='Libellé de la ligne')),
                ('ref_dgi', models.CharField(blank=True, default='', help_text='Ex. AD, AE, AJ... issu du fichier liasse officiel', max_length=10, verbose_name='Code REF officiel DGI')),
                ('cellule_dgi', models.CharField(blank=True, default='', help_text="Ex. 'NOTE 3A!D17' — onglet + adresse de cellule", max_length=30, verbose_name='Cellule dans le fichier officiel')),
                ('prefixe_comptes', models.CharField(help_text="Ex. '21' ou '211,212,213'", max_length=100, verbose_name='Préfixe(s) de comptes')),
                ('source', models.CharField(choices=[('solde_initial', 'Solde initial (ouverture)'), ('mouvement_debit', 'Mouvement débit (augmentations)'), ('mouvement_credit', 'Mouvement crédit (diminutions)'), ('solde_final', 'Solde final (clôture)')], default='solde_final', max_length=20, verbose_name='Colonne source de la balance')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Ligne de note (référentiel)',
                'verbose_name_plural': 'Lignes de notes (référentiel)',
                'ordering': ['regime_liasse', 'code_note', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.IntegerField(verbose_name='Exercice')),
                ('regime_liasse', models.CharField(choices=[('NO', 'Système Normal'), ('MT', 'Système Minimal de Trésorerie'), ('BA', 'Banques'), ('SGI', "Sociétés de Gestion et d'Intermédiation"), ('MF', 'Microfinance'), ('AV', 'Assurance Vie'), ('AN', 'Assurance Non-Vie')], default='NO', max_length=5, verbose_name='Régime de liasse')),
                ('importee_le', models.DateTimeField(auto_now_add=True, verbose_name='Importée le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='clients.client')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'unique_together': {('client', 'exercice')},
            },
        ),
        migrations.CreateModel(
            name='LigneBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=15, verbose_name='N° de compte')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé du compte')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde initial (N-1)')),
                ('mouvement_debit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Mouvement débit')),
                ('mouvement_credit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Mouvement crédit')),
                ('solde_final', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde final (N)')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.balance')),
            ],
            options={
                'verbose_name': 'Ligne de balance',
                'verbose_name_plural': 'Lignes de balance',
                'ordering': ['compte'],
            },
        ),
        migrations.CreateModel(
            name='NoteAnnexeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_liasse', models.CharField(default='NO', max_length=5, verbose_name='Régime de liasse')),
                ('code_note', models.CharField(help_text='Ex. NOTE 3A, NOTE 4, NOTE 21', max_length=15, verbose_name='Code note')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé officiel')),
                ('type_note', models.CharField(choices=[('mouvements', "Mouvements de l'exercice"), ('situation', 'Situation à la clôture'), ('comparatif', 'Comparatif N / N-1'), ('texte', 'Informations qualitatives / texte libre')], default='situation', max_length=20, verbose_name='Type de note')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage dans la liasse")),
            ],
            options={
                'verbose_name': 'Note annexe (référentiel maître)',
                'verbose_name_plural': 'Notes annexes (référentiel maître)',
                'ordering': ['regime_liasse', 'ordre'],
                'unique_together': {('regime_liasse', 'code_note')},
            },
        ),
    ]
