"""
Peuplement complet du plan comptable general SYSCOHADA (version revisee).
Source : PLAN_COMPTABLE_SYSCOHADA_REVISE.xlsx (colonnes "NOUVEAU PLAN DE COMPTES"),
fourni par le cabinet. 1398 comptes, classes 1 a 9, aucun doublon.
Referentiel universel -- valable pour tous les clients, tous regimes de liasse.
"""
from django.db import migrations

# (code, libelle, classe)
COMPTES_SYSCOHADA = [
    ("10", "CAPITAL", 1),
    ("11", "RESERVES", 1),
    ("12", "REPORT A NOUVEAU", 1),
    ("13", "RESULTAT NET DE L'EXERCICE", 1),
    ("14", "SUBVENTIONS D'INVESTISSEMENT", 1),
    ("15", "PROVISIONS REGLEMENTEES ET FONDS ASSIMILES", 1),
    ("16", "EMPRUNTS ET DETTES ASSIMILEES", 1),
    ("17", "DETTES DE LOCATION-ACQUISITION", 1),
    ("18", "DETTES LIEES A DES PARTICIPATIONS ET COMPTES  DE LIAISON DES  ETABLISSEMENTS ET SOCIETES EN PARTICIPATION", 1),
    ("19", "PROVISIONS POUR RISQUES ET CHARGES", 1),
    ("21", "IMMOBILISATIONS INCORPORELLES", 2),
    ("22", "TERRAINS", 2),
    ("23", "BATIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS", 2),
    ("24", "MATERIEL, MOBILIER ET ACTIFS BIOLOGIQUES", 2),
    ("25", "AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS", 2),
    ("26", "TITRES DE PARTICIPATION", 2),
    ("27", "AUTRES IMMOBLISATIONS FINANCIERES", 2),
    ("28", "AMORTISSEMENTS", 2),
    ("29", "DEPRECIATIONS DES IMMOBILISATIONS", 2),
    ("31", "MARCHANDISES", 3),
    ("32", "MATIERES PREMIERES ET FOURNITURES LIEES", 3),
    ("33", "AUTRES APPROVISIONNEMENTS", 3),
    ("34", "PRODUITS EN COURS", 3),
    ("35", "SERVICES EN COURS", 3),
    ("36", "PRODUITS FINIS", 3),
    ("37", "PRODUITS INTERMEDIAIRES ET RESIDUELS", 3),
    ("38", "STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DEPOT", 3),
    ("39", "DEPRECIATIONS DES STOCKS ET ENCOURS DE PRODUCTION", 3),
    ("40", "FOURNISSEURS ET COMPTES RATTACHES", 4),
    ("41", "CLIENTS ET COMPTES RATTACHES", 4),
    ("42", "PERSONNEL", 4),
    ("43", "ORGANISMES SOCIAUX", 4),
    ("44", "ETAT ET COLLECTIVITES PUBLIQUES", 4),
    ("45", "ORGANISMES INTERNATIONAUX", 4),
    ("46", "APPORTEURS, ASSOCIES ET GROUPE", 4),
    ("47", "DEBITEURS ET CREDITEURS DIVERS", 4),
    ("48", "CREANCES ET DETTES HORS ACTIVITES ORDINAIRES (HAO)", 4),
    ("49", "DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME (TIERS)", 4),
    ("50", "TITRES DE PLACEMENT", 5),
    ("51", "VALEURS A ENCAISSER", 5),
    ("52", "BANQUES", 5),
    ("53", "ETABLISSEMENTS FINANCIERS ET ASSIMILES", 5),
    ("54", "INSTRUMENTS DE TRESORERIE", 5),
    ("55", "INSTRUMENTS DE MONNAIE ELECTRONIQUE", 5),
    ("56", "BANQUES, CREDITS DE TRESORERIE ET D'ESCOMPTE", 5),
    ("57", "CAISSE", 5),
    ("58", "REGIES D'AVANCES, ACCREDITIFS ET VIREMENTS INTERNES", 5),
    ("59", "DEPRECIATIONS ET PROVISIONS POUR RISQUE A COURT TERME", 5),
    ("60", "ACHATS ET VARIATIONS DE STOCKS", 6),
    ("61", "TRANSPORTS", 6),
    ("62", "SERVICES EXTERIEURS", 6),
    ("63", "AUTRES SERVICES EXTERIEURS", 6),
    ("64", "IMPOTS ET TAXES", 6),
    ("65", "AUTRES CHARGES", 6),
    ("66", "CHARGES DE PERSONNEL", 6),
    ("67", "FRAIS FINANCIERS ET CHARGES ASSIMILEES", 6),
    ("68", "DOTATIONS AUX AMORTISSEMENTS", 6),
    ("69", "DOTATIONS AUX PROVISIONS ET AUX DEPRECIATIONS", 6),
    ("70", "VENTES", 7),
    ("71", "SUBVENTIONS D'EXPLOITATION", 7),
    ("72", "PRODUCTION IMMOBILISEE", 7),
    ("73", "VARIATIONS DES STOCKS DE BIENS ET DE SERVICES PRODUITS", 7),
    ("75", "AUTRES PRODUITS", 7),
    ("77", "REVENUS FINANCIERS ET PRODUITS ASSIMILES", 7),
    ("78", "TRANSFERTS DE CHARGES", 7),
    ("79", "REPRISES DE PROVISIONS, DE DEPRECIATIONS ET AUTRES", 7),
    ("81", "VALEURS COMPTABLES DES CESSIONS D'IMMOBILISATIONS", 8),
    ("82", "PRODUITS DES CESSIONS D'IMMOBILISATIONS", 8),
    ("83", "CHARGES HORS ACTIVITES ORDINAIRES", 8),
    ("84", "PRODUITS HORS ACTIVITES ORDINAIRES", 8),
    ("85", "DOTATIONS HORS ACTIVITES ORDINAIRES", 8),
    ("86", "REPRISES DE CHARGES, PROVISIONS ET DEPRECIATIONS HAO.", 8),
    ("87", "PARTICIPATION DES TRAVAILLEURS", 8),
    ("88", "SUBVENTIONS D'EQUILIBRE", 8),
    ("89", "IMPOTS SUR LE RESULTAT", 8),
    ("91", "CONTREPARTIES DES ENGAGEMENTS", 9),
    ("92", "COMPTES REFLECHIS", 9),
    ("93", "COMPTES DE RECLASSEMENTS", 9),
    ("94", "COMPTES DE COUTS", 9),
    ("95", "COMPTES DE STOCKS", 9),
    ("96", "COMPTES D'ECARTS SUR COUTS PREETABLIS", 9),
    ("97", "COMPTES DE DIFFERENCES DE TRAITEMENT COMPTABLE", 9),
    ("98", "COMPTES DE RESULTATS", 9),
    ("99", "COMPTES DE LIAISONS INTERNES", 9),
    ("101", "CAPITAL SOCIAL", 1),
    ("102", "CAPITAL PAR DOTATION", 1),
    ("103", "CAPITAL PERSONNEL", 1),
    ("104", "COMPTE DE L'EXPLOITANT", 1),
    ("105", "PRIMES LIEES AU CAPITAL SOCIAL", 1),
    ("106", "ECARTS DE REEVALUATION", 1),
    ("109", "APPORTEURS, CAPITAL SOUSCRIT, NON APPELE", 1),
    ("111", "RESERVE LEGALE", 1),
    ("112", "RESERVES STATUTAIRES OU CONTRACTUELLES", 1),
    ("113", "RESERVES REGLEMENTEES", 1),
    ("118", "AUTRES RESERVES", 1),
    ("121", "REPORT A NOUVEAU CREDITEUR", 1),
    ("129", "REPORT A NOUVEAU DEBITEUR", 1),
    ("130", "RESULTAT EN INSTANCE D’AFFECTATION", 1),
    ("131", "RESULTAT NET : BENEFICE", 1),
    ("132", "MARGE COMMERCIALE (MC)", 1),
    ("133", "VALEUR AJOUTEE (V.A.)", 1),
    ("134", "EXCEDENT BRUT D'EXPLOITATION (E.B.E.)", 1),
    ("135", "RESULTAT D'EXPLOITATION (R.E.)", 1),
    ("136", "RESULTAT FINANCIER (R.F.)", 1),
    ("137", "RESULTAT DES ACTIVITES ORDINAIRES (R.A.O.)", 1),
    ("138", "RESULTAT HORS ACTIVITES ORDINAIRES (R.H.A.O.)", 1),
    ("139", "RESULTAT NET : PERTE", 1),
    ("141", "SUBVENTIONS D'EQUIPEMENT", 1),
    ("148", "AUTRES SUBVENTIONS D'INVESTISSEMENT", 1),
    ("151", "AMORTISSEMENTS DEROGATOIRES", 1),
    ("152", "PLUS-VALUES DE CESSION A REINVESTIR", 1),
    ("153", "FONDS REGLEMENTES", 1),
    ("154", "PROVISIONS SPECIALES DE REEVALUATION", 1),
    ("155", "PROVISIONS REGLEMENTEES RELATIVES AUX IMMOBILISATIONS", 1),
    ("156", "PROVISIONS REGLEMENTEES RELATIVES AUX STOCKS", 1),
    ("157", "PROVISIONS POUR INVESTISSEMENT", 1),
    ("158", "AUTRES PROVISIONS ET FONDS REGLEMENTES", 1),
    ("161", "EMPRUNTS OBLIGATAIRES", 1),
    ("162", "EMPRUNTS ET DETTES AUPRES DES ETABLISSEMENTS DE CREDIT", 1),
    ("163", "AVANCES RECUES DE L'ETAT", 1),
    ("164", "AVANCES RECUES ET COMPTES COURANTS BLOQUES", 1),
    ("165", "DEPOTS ET CAUTIONNEMENTS RECUES", 1),
    ("166", "INTERETS COURUS", 1),
    ("167", "AVANCES ASSORTIES DE CONDITIONS PARTICULIERES", 1),
    ("168", "AUTRES EMPRUNTS ET DETTES", 1),
    ("172", "DETTES DE LOCATION-ACQUISITION / CREDIT-BAIL IMMOBILIER", 1),
    ("173", "DETTES DE LOCATION-ACQUISITION / CREDIT-BAIL MOBILIER", 1),
    ("174", "DETTES DE LOCATION-ACQUISITION / LOCATION-VENTE", 1),
    ("176", "INTERETS COURUS", 1),
    ("178", "AUTRES DETTES DE LOCATION-ACQUISITION", 1),
    ("181", "DETTES LIEES A DES PARTICIPATIONS", 1),
    ("182", "DETTES LIEES A DES SOCIETES EN PARTICIPATION", 1),
    ("183", "INTERETS COURUS SUR DETTES LIEES A DES PARTICIPATIONS", 1),
    ("184", "COMPTES PERMANENTS BLOQUES DES ETABLISSEMENTS ET SUCCURSALES", 1),
    ("185", "COMPTES PERMANENTS NON BLOQUES DES ETABLISSEMENTS ET SUCCURSALES", 1),
    ("186", "COMPTES DE LIAISON CHARGES", 1),
    ("187", "COMPTES DE LIAISON PRODUITS", 1),
    ("188", "COMPTES DE LIAISON DES SOCIETES EN PARTICIPATION", 1),
    ("191", "PROVISIONS POUR LITIGES", 1),
    ("192", "PROVISIONS POUR GARANTIES DONNEES AUX CLIENTS", 1),
    ("193", "PROVISIONS POUR PERTES SUR MARCHES A ACHEVEMENT FUTUR", 1),
    ("194", "PROVISIONS POUR PERTES DE CHANGE", 1),
    ("195", "PROVISIONS POUR IMPOTS", 1),
    ("196", "PROVISIONS POUR PENSIONS ET OBLIGATIONS SIMILAIRES", 1),
    ("197", "PROVISIONS POUR RESTRUCTURATION", 1),
    ("198", "AUTRES PROVISIONS POUR RISQUES ET CHARGES", 1),
    ("211", "FRAIS  DE DEVELOPPEMENT", 2),
    ("212", "BREVETS, LICENCES, CONCESSIONS ET DROITS SIMILAIRES", 2),
    ("213", "LOGICIELS ET SITES INTERNET", 2),
    ("214", "MARQUES", 2),
    ("215", "FONDS COMMERCIAL", 2),
    ("216", "DROIT AU BAIL", 2),
    ("217", "INVESTISSEMENTS DE CREATION", 2),
    ("218", "AUTRES DROITS ET VALEURS INCORPORELS", 2),
    ("219", "IMMOBILISATIONS INCORPORELLES EN COURS", 2),
    ("221", "TERRAINS AGRICOLES ET FORESTIERS", 2),
    ("222", "TERRAINS NUS", 2),
    ("223", "TERRAINS BATIS", 2),
    ("224", "TRAVAUX DE MISE EN VALEUR DES TERRAINS", 2),
    ("225", "TERRAINS DE CARRIERES – TREFONDS", 2),
    ("226", "TERRAINS AMENAGES", 2),
    ("227", "TERRAINS MIS EN CONCESSION", 2),
    ("228", "AUTRES TERRAINS", 2),
    ("229", "AMENAGEMENTS DE TERRAINS EN COURS", 2),
    ("231", "BATIMENTS INDUSTRIELS, AGRICOLES, ADMINISTRATIFS  ET COMMERCIAUX SUR SOL PROPRE", 2),
    ("232", "BATIMENTS INDUSTRIELS, AGRICOLES, ADMINISTRATIFS ET COMMERCIAUX SUR SOL D’AUTRUI", 2),
    ("233", "OUVRAGES D’INFRASTRUCTURE", 2),
    ("234", "AMENAGEMENTS, AGENCEMENTS ET INSTALLATIONS TECHNIQUES", 2),
    ("235", "AMENAGEMENTS DE BUREAUX", 2),
    ("237", "BATIMENTS INDUSTRIELS, AGRICOLES ET COMMERCIAUX MIS EN CONCESSION", 2),
    ("238", "AUTRES INSTALLATIONS ET AGENCEMENTS", 2),
    ("239", "BATIMENTS AMENAGEMENTS, AGENCEMENTS  ET INSTALLATIONS EN COURS", 2),
    ("241", "MATERIEL ET OUTILLAGE INDUSTRIEL ET COMMERCIAL", 2),
    ("242", "MATERIEL ET OUTILLAGE AGRICOLE", 2),
    ("243", "MATERIEL D’EMBALLAGE RECUPERABLE ET IDENTIFIABLE", 2),
    ("244", "MATERIEL ET MOBILIER", 2),
    ("245", "MATERIEL DE TRANSPORT", 2),
    ("246", "ACTIFS BIOLOGIQUES", 2),
    ("247", "AGENCEMENTS, AMENAGEMENTS DU MATERIEL ET DES ACTIFS BIOLOGIQUES", 2),
    ("248", "AUTRES MATERIELS ET MOBILIERS", 2),
    ("249", "MATERIELS ET ACTIFS BIOLOGIQUES EN COURS", 2),
    ("251", "AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS INCORPORELLES", 2),
    ("252", "AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS CORPORELLES", 2),
    ("261", "TITRES DE PARTICIPATION DANS DES ENTITES SOUS CONTROLE EXCLUSIF", 2),
    ("262", "TITRES DE PARTICIPATION DANS DES ENTITES SOUS CONTROLE  CONJOINT", 2),
    ("263", "TITRES DE PARTICIPATION DANS DES ENTITESCONFERANT UNE INFLUENCE NOTABLE", 2),
    ("265", "PARTICIPATIONS DANS DES ORGANISMES PROFESSIONNELS", 2),
    ("266", "PARTS DANS DES GROUPEMENTS D’INTERET ECONOMIQUE (G.I.E.)", 2),
    ("268", "AUTRES TITRES DE PARTICIPATION", 2),
    ("271", "PRETS ET CREANCES", 2),
    ("272", "PRETS AU PERSONNEL", 2),
    ("273", "CREANCES SUR L’ETAT", 2),
    ("274", "TITRES IMMOBILISES", 2),
    ("275", "DEPOTS ET CAUTIONNEMENTS VERSES", 2),
    ("276", "INTERETS COURUS", 2),
    ("277", "CREANCES RATTACHEES A DES PARTICIPATIONS ET AVANCES A DES G.I.E.", 2),
    ("278", "IMMOBILISATIONS FINANCIERES DIVERSES", 2),
    ("281", "AMORTISSEMENTS DES IMMOBILISATIONS INCORPORELLES", 2),
    ("282", "AMORTISSEMENTS DES TERRAINS", 2),
    ("283", "AMORTISSEMENTS DES BATIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS", 2),
    ("284", "AMORTISSEMENTS DU MATERIEL", 2),
    ("291", "DEPRECIATIONS DES IMMOBILISATIONS INCORPORELLES", 2),
    ("292", "DEPRECIATIONS DES TERRAINS", 2),
    ("293", "DEPRECIATIONS DES BATIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS", 2),
    ("294", "DEPRECIATIONS DE MATERIEL, DU MOBILIER ET DE L’ACTIF BIOLOGIQUE", 2),
    ("295", "DEPRECIATIONS DES AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS", 2),
    ("296", "DEPRECIATIONS DES TITRES DE PARTICIPATION", 2),
    ("297", "DEPRECIATIONS DES AUTRES IMMOBILISATIONS FINANCIERES", 2),
    ("311", "MARCHANDISES A", 3),
    ("312", "MARCHANDISES B", 3),
    ("313", "ACTIFS BIOLOGIQUES", 3),
    ("318", "MARCHANDISES HORS ACTIVITES ORDINAIRES (H.A.O.)", 3),
    ("321", "MATIERES A", 3),
    ("322", "MATIERES B", 3),
    ("323", "FOURNITURES (A,B)", 3),
    ("331", "MATIERES CONSOMMABLES", 3),
    ("332", "FOURNITURES D'ATELIER ET D'USINE", 3),
    ("333", "FOURNITURES DE MAGASIN", 3),
    ("334", "FOURNITURES DE BUREAU", 3),
    ("335", "EMBALLAGES", 3),
    ("338", "AUTRES MATIERES", 3),
    ("341", "PRODUITS EN COURS", 3),
    ("342", "TRAVAUX EN COURS", 3),
    ("343", "PRODUITS INTERMEDIAIRES EN COURS", 3),
    ("344", "PRODUITS RESIDUELS EN COURS", 3),
    ("345", "ACTIFS BIOLOGIQUES", 3),
    ("351", "ETUDES EN COURS", 3),
    ("352", "PRESTATIONS DE SERVICES EN COURS", 3),
    ("361", "PRODUITS FINIS A", 3),
    ("362", "PRODUITS FINIS B", 3),
    ("363", "ACTIFS BIOLOGIQUES", 3),
    ("371", "PRODUITS INTERMEDIAIRES", 3),
    ("372", "PRODUITS RESIDUELS", 3),
    ("373", "ACTIFS BIOLOGIQUES", 3),
    ("381", "MARCHANDISES EN COURS DE ROUTE", 3),
    ("382", "MATIERES PREMIERES ET FOURNITURES LIEES EN COURS DE ROUTE", 3),
    ("383", "AUTRES APPROVISIONNEMENTS EN COURS DE ROUTE", 3),
    ("386", "PRODUITS FINIS EN COURS DE ROUTE", 3),
    ("387", "STOCK EN CONSIGNATION OU EN DEPOT", 3),
    ("388", "STOCK PROVENANT D'IMMOBILISATIONS MISES HORS SERVICE OU AU REBUT", 3),
    ("391", "DEPRECIATIONS DES STOCKS DE MARCHANDISES", 3),
    ("392", "DEPRECIATIONS DES STOCKS DE MATIERES PREMIERES ET FOURNITURES LIEES", 3),
    ("393", "DEPRECIATIONS DES STOCKS D'AUTRES APPROVISIONNEMENTS", 3),
    ("394", "DEPRECIATIONS DES PRODUCTIONS EN COURS", 3),
    ("395", "DEPRECIATIONS DES SERVICES EN COURS", 3),
    ("396", "DEPRECIATIONS DES STOCKS DE PRODUITS FINIS", 3),
    ("397", "DEPRECIATIONS DES STOCKS DE PRODUITS INTERMEDIAIRES ET RESIDUELS", 3),
    ("398", "DEPRECIATIONS DES STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DEPOT", 3),
    ("401", "FOURNISSEURS, DETTES EN COMPTE", 4),
    ("402", "FOURNISSEURS, EFFETS A PAYER", 4),
    ("404", "FOURNISSEURS, ACQUISITIONS COURANTES D’IMMOBILISATIONS", 4),
    ("408", "FOURNISSEURS, FACTURES NON PARVENUES", 4),
    ("409", "FOURNISSEURS DEBITEURS", 4),
    ("411", "CLIENTS", 4),
    ("412", "CLIENTS, EFFETS A RECEVOIR EN PORTEFEUILLE", 4),
    ("413", "CLIENTS, CHEQUES, EFFETS ET AUTRES VALEURS IMPAYES", 4),
    ("414", "CREANCES SUR CESSIONS COURANTES D'IMMOBILISATIONS", 4),
    ("415", "CLIENTS, EFFETS ESCOMPTES NON ECHUS", 4),
    ("416", "CREANCES CLIENTS LITIGIEUSES OU DOUTEUSES", 4),
    ("418", "CLIENTS, PRODUITS A RECEVOIR", 4),
    ("419", "CLIENTS CREDITEURS", 4),
    ("421", "PERSONNEL, AVANCES ET ACOMPTES", 4),
    ("422", "PERSONNEL, REMUNERATIONS DUES", 4),
    ("423", "PERSONNEL, OPPOSITIONS, SAISIES-ARRETS", 4),
    ("424", "PERSONNEL, OEUVRES SOCIALES INTERNES", 4),
    ("425", "REPRESENTANTS DU PERSONNEL", 4),
    ("426", "PERSONNEL, PARTICIPATION AUX BENEFICES ET AU CAPITAL", 4),
    ("427", "PERSONNEL – DEPOTS", 4),
    ("428", "PERSONNEL, CHARGES A PAYER ET PRODUITS A RECEVOIR", 4),
    ("431", "SECURITE SOCIALE", 4),
    ("432", "CAISSES DE RETRAITE COMPLEMENTAIRE", 4),
    ("433", "AUTRES ORGANISMES SOCIAUX", 4),
    ("438", "ORGANISMES SOCIAUX, CHARGES À PAYER ET PRODUITS À RECEVOIR", 4),
    ("441", "ETAT, IMPOT SUR LES BENEFICES", 4),
    ("442", "ETAT, AUTRES IMPOTS ET TAXES", 4),
    ("443", "ETAT, T.V.A. FACTUREE", 4),
    ("444", "ETAT, T.V.A. DUE OU CREDIT DE T.V.A.", 4),
    ("445", "ETAT, T.V.A. RECUPERABLE", 4),
    ("446", "ETAT, AUTRES TAXES SUR LE CHIFFRE D'AFFAIRES", 4),
    ("447", "", 4),
    ("448", "ETAT, CHARGES A PAYER ET PRODUITS A RECEVOIR", 4),
    ("449", "ETAT, CREANCES ET DETTES DIVERSES", 4),
    ("451", "OPERATIONS AVEC LES ORGANISMES AFRICAINS", 4),
    ("452", "OPERATIONS AVEC LES AUTRES ORGANISMES INTERNATIONAUX", 4),
    ("458", "ORGANISMES INTERNATIONAUX, FONDS DE DOTATION ET SUBVENTIONS A RECEVOIR", 4),
    ("461", "APPORTEURS, OPERATIONS SUR LE CAPITAL", 4),
    ("462", "ASSOCIES (2), COMPTES COURANTS", 4),
    ("463", "ASSOCIES (2), OPERATIONS FAITES EN COMMUN ET GIE", 4),
    ("465", "ASSOCIES (2), DIVIDENDES A PAYER", 4),
    ("466", "GROUPE, COMPTES COURANTS", 4),
    ("467", "APPORTEURS RESTANT DÛ SUR CAPITAL APPELE", 4),
    ("469", "ENTITE, DIVIDENDES A RECEVOIR", 4),
    ("471", "DEBITEURS ET CREDITEURS DIVERS", 4),
    ("472", "CREANCES ET DETTES SUR TITRES DE PLACEMENT", 4),
    ("473", "INTERMEDIAIRES - OPERATIONS FAITES POUR COMPTE DE TIERS", 4),
    ("474", "COMPTE DE REPARTITION PERIODIQUE DES CHARGES ET DES PRODUITS", 4),
    ("475", "COMPTE TRANSITOIRE, AJUSTEMENT SPECIAL LIE A LA REVISION DU SYSCOHADA", 4),
    ("476", "CHARGES CONSTATEES D'AVANCE", 4),
    ("477", "PRODUITS CONSTATES D'AVANCE", 4),
    ("478", "ECARTS DE CONVERSION - ACTIF", 4),
    ("479", "ECARTS DE CONVERSION - PASSIF", 4),
    ("481", "FOURNISSEURS D'INVESTISSEMENTS", 4),
    ("482", "FOURNISSEURS D'INVESTISSEMENTS, EFFETS A PAYER", 4),
    ("484", "AUTRES DETTES HORS ACTIVITES ORDINAIRES (H.A.O.)", 4),
    ("485", "CREANCES SUR CESSIONS D'IMMOBILISATIONS", 4),
    ("488", "AUTRES CREANCES HORS ACTIVITES ORDINAIRES (H.A.O.)", 4),
    ("490", "DEPRECIATIONS DES COMPTES FOURNISSEURS", 4),
    ("491", "DEPRECIATIONS DES COMPTES CLIENTS", 4),
    ("492", "DEPRECIATIONS DES COMPTES PERSONNEL", 4),
    ("493", "DEPRECIATIONS DES COMPTES ORGANISMES SOCIAUX", 4),
    ("494", "DEPRECIATIONS DES COMPTES ETAT ET COLLECTIVITES PUBLIQUES", 4),
    ("495", "DEPRECIATIONS DES COMPTES ORGANISMES INTERNATIONAUX", 4),
    ("496", "DEPRECIATIONS DES COMPTES  ASSOCIES ET GROUPE", 4),
    ("497", "DEPRECIATIONS DES COMPTES DEBITEURS DIVERS", 4),
    ("498", "DEPRECIATIONS DES COMPTES DE CREANCES H.A.O.", 4),
    ("499", "PROVISIONS POUR RISQUES A COURT TERME", 4),
    ("501", "TITRES DU TRESOR ET BONS DE CAISSE A COURT TERME", 5),
    ("502", "ACTIONS", 5),
    ("503", "OBLIGATIONS", 5),
    ("504", "BONS DE SOUSCRIPTION", 5),
    ("505", "TITRES NEGOCIABLES HORS REGION", 5),
    ("506", "INTERETS COURUS", 5),
    ("508", "AUTRES TITRES DE PLACEMENT ET CREANCES ASSIMILEES", 5),
    ("511", "EFFETS A ENCAISSER", 5),
    ("512", "EFFETS A L'ENCAISSEMENT", 5),
    ("513", "CHEQUES A ENCAISSER", 5),
    ("514", "CHEQUES A L'ENCAISSEMENT", 5),
    ("515", "CARTES DE CREDIT A ENCAISSER", 5),
    ("518", "AUTRES VALEURS A L'ENCAISSEMENT", 5),
    ("521", "BANQUES LOCALES", 5),
    ("522", "BANQUES AUTRES ETATS REGION", 5),
    ("523", "BANQUES AUTRES ETATS ZONE MONETAIRE", 5),
    ("524", "BANQUES HORS ZONE MONETAIRE", 5),
    ("525", "BANQUES DEPOT  A TERME", 5),
    ("526", "BANQUES, INTERETS  COURUS", 5),
    ("531", "CHEQUES POSTAUX", 5),
    ("532", "TRESOR", 5),
    ("533", "SOCIETES DE GESTION ET D'INTERMEDIATION (S.G.I.)", 5),
    ("536", "ETABLISSEMENTS FINANCIERS, INTERETS COURUS", 5),
    ("538", "AUTRES ORGANISMES FINANCIERS", 5),
    ("541", "OPTIONS DE TAUX D'INTERET", 5),
    ("542", "OPTIONS DE TAUX DE CHANGE", 5),
    ("543", "OPTIONS DE TAUX BOURSIERS", 5),
    ("544", "INSTRUMENTS DE MARCHES A TERME", 5),
    ("545", "AVOIRS D'OR ET AUTRES METAUX PRECIEUX (4)", 5),
    ("551", "MONNAIE ELECTRONIQUE - CARTE CARBURANT", 5),
    ("552", "MONNAIE ELECTRONIQUE - TELEPHONE PORTABLE", 5),
    ("553", "MONNAIE ELECTRONIQUE- CARTE PEAGE", 5),
    ("554", "PORTE -MONNAIE ELECTRONIQUE", 5),
    ("558", "AUTRES INSTRUMENTS DE MONNAIES ELECTRONIQUES", 5),
    ("561", "CREDITS DE TRESORERIE", 5),
    ("564", "ESCOMPTE DE CREDITS DE CAMPAGNE", 5),
    ("565", "ESCOMPTE DE CREDITS ORDINAIRES", 5),
    ("566", "BANQUES,  CREDITS DE TRESORERIE, INTERETS  COURUS", 5),
    ("571", "CAISSE SIEGE SOCIAL", 5),
    ("572", "CAISSE SUCCURSALE A", 5),
    ("573", "CAISSE SUCCURSALE B", 5),
    ("581", "REGIES D'AVANCE", 5),
    ("582", "ACCREDITIFS", 5),
    ("585", "VIREMENTS DE FONDS", 5),
    ("588", "AUTRES VIREMENTS INTERNES", 5),
    ("590", "DEPRECIATIONS DES TITRES DE PLACEMENT", 5),
    ("591", "DEPRECIATIONS DES TITRES ET VALEURS A ENCAISSER", 5),
    ("592", "DEPRECIATIONS DES COMPTES BANQUES", 5),
    ("593", "DEPRECIATIONS DES COMPTES ETABLISSEMENTS FINANCIERS ET ASSIMILES", 5),
    ("594", "DEPRECIATIONS DES COMPTES D’INSTRUMENTS DE TRESORERIE", 5),
    ("599", "PROVISIONS POUR RISQUE A COURT TERME  A CARACTERE FINANCIER", 5),
    ("601", "ACHATS DE MARCHANDISES", 6),
    ("602", "ACHATS DE MATIERES PREMIERES ET FOURNITURES LIEES", 6),
    ("603", "VARIATIONS DES STOCKS DE BIENS ACHETES", 6),
    ("604", "ACHATS STOCKES DE MATIERES ET FOURNITURES CONSOMMABLES", 6),
    ("605", "AUTRES ACHATS", 6),
    ("608", "ACHATS D'EMBALLAGES", 6),
    ("612", "TRANSPORTS SUR VENTES", 6),
    ("613", "TRANSPORTS POUR LE COMPTE DE TIERS", 6),
    ("614", "TRANSPORTS DU PERSONNEL", 6),
    ("616", "TRANSPORTS DE PLIS", 6),
    ("618", "AUTRES FRAIS DE TRANSPORT", 6),
    ("621", "SOUS-TRAITANCE GENERALE", 6),
    ("622", "LOCATIONS,  CHARGES LOCATIVES", 6),
    ("623", "REDEVANCES DE LOCATION-ACQUISITION", 6),
    ("624", "ENTRETIEN, REPARATIONS, REMISE EN ETAT ET MAINTENANCE", 6),
    ("625", "PRIMES D'ASSURANCE", 6),
    ("626", "ETUDES, RECHERCHES ET DOCUMENTATION", 6),
    ("627", "PUBLICITE, PUBLICATIONS, RELATIONS PUBLIQUES", 6),
    ("628", "FRAIS DE TELECOMMUNICATIONS", 6),
    ("631", "FRAIS BANCAIRES", 6),
    ("632", "REMUNERATIONS D'INTERMEDIAIRES ET DE CONSEILS", 6),
    ("633", "FRAIS DE FORMATION DU PERSONNEL", 6),
    ("634", "REDEVANCES POUR BREVETS, LICENCES, LOGICIELS, CONCESSIONS, DROITS  ET VALEURS SIMILAIRES", 6),
    ("635", "COTISATIONS", 6),
    ("637", "REMUNERATIONS DE PERSONNEL EXTERIEUR A L’ENTITE", 6),
    ("638", "AUTRES CHARGES EXTERNES", 6),
    ("641", "IMPOTS ET TAXES DIRECTS", 6),
    ("645", "IMPOTS ET TAXES INDIRECTS", 6),
    ("646", "DROITS D'ENREGISTREMENT", 6),
    ("647", "PENALITES, AMENDES FISCALES", 6),
    ("648", "AUTRES IMPOTS ET TAXES", 6),
    ("651", "PERTES SUR CREANCES CLIENTS ET AUTRES DEBITEURS", 6),
    ("652", "QUOTE-PART DE RESULTAT SUR OPERATIONS FAITES EN COMMUN", 6),
    ("654", "VALEURS COMPTABLES DES CESSIONS COURANTES D'IMMOBILISATIONS", 6),
    ("656", "PERTE DE CHANGE SUR CREANCES ET DETTES COMMERCIALE", 6),
    ("657", "PENALITES ET AMENDES PENALES", 6),
    ("658", "CHARGES DIVERSES", 6),
    ("659", "CHARGES POUR DEPRECIATIONS ET PROVISIONS POUR RISQUES   A COURT TERME D'EXPLOITATION", 6),
    ("661", "REMUNERATIONS DIRECTES VERSEES AU PERSONNEL NATIONAL", 6),
    ("662", "REMUNERATIONS DIRECTES VERSEES AU PERSONNEL NON NATIONAL", 6),
    ("663", "INDEMNITES FORFAITAIRES VERSEES AU PERSONNEL", 6),
    ("664", "CHARGES SOCIALES", 6),
    ("666", "REMUNERATIONS ET CHARGES SOCIALES DE L'EXPLOITANT INDIVIDUEL", 6),
    ("667", "REMUNERATION TRANSFEREE DE PERSONNEL EXTERIEUR", 6),
    ("668", "AUTRES CHARGES SOCIALES", 6),
    ("671", "INTERETS DES EMPRUNTS", 6),
    ("672", "INTERETS DANS LOYERS DE LOCATION ACQUISITION", 6),
    ("673", "ESCOMPTES ACCORDES", 6),
    ("674", "AUTRES INTERETS", 6),
    ("675", "ESCOMPTES DES EFFETS DE COMMERCE", 6),
    ("676", "PERTES DE CHANGE FINANCIERES", 6),
    ("677", "PERTES SUR TITRES DE PLACEMENT", 6),
    ("678", "PERTES ET CHARGES SUR RISQUES FINANCIERS", 6),
    ("679", "CHARGES POUR DEPRECIATIONS  ET PROVISIONS POUR RISQUES A COURT TERME FINANCIERES", 6),
    ("681", "DOTATIONS AUX AMORTISSEMENTS D'EXPLOITATION", 6),
    ("691", "DOTATIONS AUX PROVISIONS ET AUX DEPRECIATIONS  D'EXPLOITATION", 6),
    ("697", "DOTATIONS AUX PROVISIONS ET AUX DEPRECIATIONS  FINANCIERES", 6),
    ("701", "VENTES DE MARCHANDISES", 7),
    ("702", "VENTES DE PRODUITS FINIS", 7),
    ("703", "VENTES DE PRODUITS INTERMEDIAIRES", 7),
    ("704", "VENTES DE PRODUITS RESIDUELS", 7),
    ("705", "TRAVAUX FACTURES", 7),
    ("706", "SERVICES VENDUS", 7),
    ("707", "PRODUITS ACCESSOIRES", 7),
    ("711", "SUR PRODUITS A L'EXPORTATION", 7),
    ("712", "SUR PRODUITS A L'IMPORTATION", 7),
    ("713", "SUR PRODUITS DE PEREQUATION", 7),
    ("714", "INDEMNITES ET SUBVENTIONS D’EXPLOITATION (entité agricole)", 7),
    ("718", "AUTRES SUBVENTIONS D'EXPLOITATION", 7),
    ("721", "IMMOBILISATIONS INCORPORELLES", 7),
    ("722", "IMMOBILISATIONS CORPORELLES", 7),
    ("724", "PRODUCTION AUTO-CONSOMMEE", 7),
    ("726", "IMMOBILISATIONS FINANCIERES (9)", 7),
    ("734", "VARIATIONS DES STOCKS DE PRODUITS EN COURS", 7),
    ("735", "VARIATIONS DES SERVICES EN COURS", 7),
    ("736", "VARIATIONS DES STOCKS DE PRODUITS FINIS", 7),
    ("737", "VARIATIONS DES STOCKS DE PRODUITS INTERMEDIAIRES ET RESIDUELS", 7),
    ("751", "PROFITS SUR CREANCES CLIENTS ET AUTRES DEBITEURS", 7),
    ("752", "QUOTE-PART DE RESULTAT SUR OPERATIONS FAITES EN COMMUN", 7),
    ("754", "PRODUITS DES CESSIONS COURANTES D'IMMOBILISATIONS", 7),
    ("756", "GAINS DE CHANGE SUR CREANCES ET DETTES COMMERCIALES", 7),
    ("758", "PRODUITS DIVERS", 7),
    ("759", "REPRISES DE CHARGES POUR DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME D'EXPLOITATION", 7),
    ("771", "INTERETS DE PRETS ET CREANCES DIVERSES", 7),
    ("772", "REVENUS DE PARTICIPATIONS ET AUTRES TITRES IMMOBILISES", 7),
    ("773", "ESCOMPTES OBTENUS", 7),
    ("774", "REVENUS DE PLACEMENT", 7),
    ("775", "INTERETS DANS LOYERS DE LOCATION-FINANCEMENT", 7),
    ("776", "GAINS DE CHANGE FINANCIERS", 7),
    ("777", "GAINS SUR CESSIONS DE TITRES DE PLACEMENT", 7),
    ("778", "GAINS SUR RISQUES FINANCIERS", 7),
    ("779", "REPRISES DE CHARGES POUR DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME FINANCIERES", 7),
    ("781", "TRANSFERTS DE CHARGES D'EXPLOITATION", 7),
    ("787", "TRANSFERTS DE CHARGES FINANCIERES", 7),
    ("791", "REPRISES DE PROVISIONS ET DEPRECIATIONS D'EXPLOITATION", 7),
    ("797", "REPRISES DE PROVISIONS ET DEPRECIATIONS  FINANCIERES", 7),
    ("798", "REPRISES D'AMORTISSEMENTS (10)", 7),
    ("799", "REPRISES DE SUBVENTIONS D’INVESTISSEMENT", 7),
    ("811", "IMMOBILISATIONS INCORPORELLES", 8),
    ("812", "IMMOBILISATIONS CORPORELLES", 8),
    ("816", "IMMOBILISATIONS FINANCIERES", 8),
    ("821", "IMMOBILISATIONS INCORPORELLES", 8),
    ("822", "IMMOBILISATIONS CORPORELLES", 8),
    ("826", "IMMOBILISATIONS FINANCIERES", 8),
    ("831", "CHARGES H.A.O. CONSTATEES", 8),
    ("833", "CHARGES LIEES AUX OPERATIONS DE RESTRUCTURATION", 8),
    ("834", "PERTES SUR CREANCES H.A.O.", 8),
    ("835", "DONS ET LIBERALITES ACCORDES", 8),
    ("836", "ABANDONS DE CREANCES CONSENTIS", 8),
    ("837", "CHARGES LIEES AUX OPERATIONS DE LIQUIDATION", 8),
    ("839", "CHARGES  POUR DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME H.A.O.", 8),
    ("841", "PRODUITS H.A.O CONSTATES", 8),
    ("843", "PRODUITS LIES AUX OPERATIONS DE RESTRUCTURATION", 8),
    ("844", "INDEMNITES ET SUBVENTIONS H.A.O. (entité agricole)", 8),
    ("845", "DONS ET LIBERALITES OBTENUS", 8),
    ("846", "ABANDONS DE CREANCES OBTENUS", 8),
    ("847", "PRODUITS LIES AUX OPERATIONS DE LIQUIDATION", 8),
    ("848", "TRANSFERTS DE CHARGES H.A.O", 8),
    ("849", "REPRISES DE CHARGES POUR DEPRECIATIONS ET PROVISIONS POUR RISQUES A COURT TERME H.A.O.", 8),
    ("851", "DOTATIONS AUX PROVISIONS REGLEMENTEES", 8),
    ("852", "DOTATIONS AUX AMORTISSEMENTS H.A.O.", 8),
    ("853", "DOTATIONS AUX DEPRECIATIONS H.A.O.", 8),
    ("854", "DOTATIONS AUX PROVISIONS POUR RISQUES ET CHARGES H.A.O.", 8),
    ("858", "AUTRES DOTATIONS H.A.O.", 8),
    ("861", "REPRISES DE PROVISIONS REGLEMENTEES", 8),
    ("862", "REPRISES D’AMORTISSEMENTS H.A.O", 8),
    ("863", "REPRISES DE DEPRECIATIONS H.A.O.", 8),
    ("864", "REPRISES DE PROVISIONS POUR RISQUES ET CHARGES H.A.O.", 8),
    ("868", "AUTRES REPRISES H.A.O.", 8),
    ("871", "PARTICIPATION LEGALE AUX BENEFICES", 8),
    ("874", "PARTICIPATION CONTRACTUELLE AUX BENEFICES", 8),
    ("878", "AUTRES PARTICIPATIONS", 8),
    ("881", "ETAT", 8),
    ("884", "COLLECTIVITES PUBLIQUES", 8),
    ("886", "GROUPE", 8),
    ("888", "AUTRES", 8),
    ("891", "IMPOTS SUR LES BENEFICES DE L'EXERCICE", 8),
    ("892", "RAPPEL D'IMPOTS SUR RESULTATS ANTERIEURS", 8),
    ("895", "IMPOT MINIMUM FORFAITAIRE (I.M.F.)", 8),
    ("899", "DEGREVEMENTS ET ANNULATIONS D’IMPOTS SUR RESULTATS ANTERIEURS", 8),
    ("905", "ENGAGEMENTS DE FINANCEMENT ACCORDES", 9),
    ("906", "ENGAGEMENTS DE GARANTIE ACCORDES", 9),
    ("907", "ENGAGEMENTS RECIPROQUES", 9),
    ("908", "AUTRES ENGAGEMENTS ACCORDES", 9),
    ("1011", "Capital souscrit, non appelé", 1),
    ("1012", "Capital souscrit, appelé, non versé", 1),
    ("1013", "Capital souscrit, appelé, versé, non amorti", 1),
    ("1014", "Capital souscrit, appelé, versé, amorti", 1),
    ("1018", "Capital souscrit soumis à des conditions particulières", 1),
    ("1021", "Dotation initiale", 1),
    ("1022", "Dotations complémentaires", 1),
    ("1028", "Autres dotations", 1),
    ("1041", "Apports temporaires", 1),
    ("1042", "Opérations courantes", 1),
    ("1043", "Rémunérations, impôts et autres charges personnelles", 1),
    ("1047", "Prélèvements d’autoconsommation", 1),
    ("1048", "Autres prélèvements", 1),
    ("1051", "Primes d'émission", 1),
    ("1052", "Primes d'apport", 1),
    ("1053", "Primes de fusion", 1),
    ("1054", "Primes de conversion", 1),
    ("1058", "Autres primes", 1),
    ("1061", "Ecarts de réévaluation légale", 1),
    ("1062", "Ecarts de réévaluation libre", 1),
    ("1131", "Réserves de plus-values nettes à long terme", 1),
    ("1132", "Réserves d’attribution gratuite d’actions au personnel salarié et aux dirigeants", 1),
    ("1133", "Réserves consécutives à l'octroi de subventions d'investissement", 1),
    ("1134", "Réserves des valeurs mobilières donnant accès au capital", 1),
    ("1138", "Autres réserves réglementées", 1),
    ("1181", "Réserves facultatives", 1),
    ("1188", "Réserves diverses", 1),
    ("1291", "Perte nette à reporter", 1),
    ("1292", "Perte - Amortissements réputés différés", 1),
    ("1301", "Résultat en instance d'affectation : Bénéfice", 1),
    ("1309", "Résultat en instance d'affectation : Perte", 1),
    ("1381", "Résultat de fusion", 1),
    ("1382", "Résultat d'apport partiel d'actif", 1),
    ("1383", "Résultat de scission", 1),
    ("1384", "Résultat de liquidation", 1),
    ("1411", "Etat", 1),
    ("1412", "Régions", 1),
    ("1413", "Départements", 1),
    ("1414", "Communes et collectivités publiques décentralisées", 1),
    ("1415", "Entités publiques ou mixtes", 1),
    ("1416", "Entités et organismes privés", 1),
    ("1417", "Organismes internationaux", 1),
    ("1418", "Autres", 1),
    ("1531", "Fonds National", 1),
    ("1532", "Prélèvement pour le Budget", 1),
    ("1551", "Reconstitution des gisements miniers et pétroliers", 1),
    ("1561", "Hausse de prix", 1),
    ("1562", "Fluctuation des cours", 1),
    ("1611", "Emprunts obligataires ordinaires", 1),
    ("1612", "Emprunts obligataires convertibles en actions", 1),
    ("1613", "Emprunts obligataires remboursables en actions", 1),
    ("1618", "Autres emprunts obligataires", 1),
    ("1651", "Dépôts", 1),
    ("1652", "Cautionnements", 1),
    ("1661", "sur emprunts obligataires", 1),
    ("1662", "sur emprunts et dettes auprès des établissements de crédit", 1),
    ("1663", "sur avances reçues de l'Etat", 1),
    ("1664", "sur avances reçues et comptes courants bloqués", 1),
    ("1665", "sur dépôts et cautionnements reçus", 1),
    ("1667", "sur avances assorties de conditions particulières", 1),
    ("1668", "sur autres emprunts et dettes", 1),
    ("1671", "Avances bloquées pour augmentation du capital", 1),
    ("1672", "Avances conditionnées par l'Etat", 1),
    ("1673", "Avances conditionnées par les autres organismes africains", 1),
    ("1674", "Avances conditionnées par les organismes internationaux", 1),
    ("1681", "Rentes viagères capitalisées", 1),
    ("1682", "Billets de fonds", 1),
    ("1683", "Dettes consécutives à des titres empruntés", 1),
    ("1684", "Emprunts participatifs", 1),
    ("1685", "Participation des travailleurs aux bénéfices", 1),
    ("1686", "Emprunts et dettes contractés auprès des autres tiers", 1),
    ("1762", "sur dettes de location-acquisition / crédit-bail immobilier", 1),
    ("1763", "sur dettes  de  location-acquisition  / crédit-bail mobilier", 1),
    ("1764", "sur dettes  de location-acquisition / location-vente", 1),
    ("1768", "sur autres dettes  de location-acquisition", 1),
    ("1811", "Dettes liées à des participations (groupe)", 1),
    ("1812", "Dettes liées à des participations (hors groupe)", 1),
    ("1961", "Provisions pour pensions et obligations similaires –engagement de retraite", 1),
    ("1962", "Actif du régime de retraite", 1),
    ("1981", "Provisions pour amendes et pénalités", 1),
    ("1983", "Provisions de propre assureur", 1),
    ("1984", "Provisions pour démantèlement et remise en état", 1),
    ("1985", "Provisions pour droits à réduction ou avantage en nature  (Chèques cadeaux, cartes de fidélité…)", 1),
    ("1988", "Provisions pour divers risques et charges", 1),
    ("2121", "Brevets", 2),
    ("2122", "Licences", 2),
    ("2123", "Concessions de service public", 2),
    ("2128", "Autres concessions et droits similaires", 2),
    ("2131", "Logiciels", 2),
    ("2132", "Sites internet", 2),
    ("2181", "Frais de prospection et d’évaluation de ressources minérales", 2),
    ("2182", "Coûts d’obtention du contrat", 2),
    ("2183", "Fichiers clients, notices, titres de journaux et magazines", 2),
    ("2184", "Coûts des franchises", 2),
    ("2188", "Divers droits et valeurs incorporels", 2),
    ("2191", "Frais de développement", 2),
    ("2193", "Logiciels et sites internet", 2),
    ("2198", "Autres droits et valeurs incorporels", 2),
    ("2211", "Terrains d'exploitation agricole", 2),
    ("2212", "Terrains d'exploitation forestière", 2),
    ("2218", "Autres terrains", 2),
    ("2221", "Terrains à bâtir", 2),
    ("2228", "Autres terrains nus", 2),
    ("2231", "pour bâtiments industriels et agricoles", 2),
    ("2232", "pour bâtiments administratifs et commerciaux", 2),
    ("2234", "pour bâtiments affectés aux autres opérations professionnelles", 2),
    ("2235", "pour bâtiments affectés aux autres opérations non professionnelles", 2),
    ("2238", "Autres terrains bâtis", 2),
    ("2241", "Plantation d'arbres et d'arbustes", 2),
    ("2245", "Améliorations du fonds", 2),
    ("2248", "Autres travaux", 2),
    ("2251", "Carrières", 2),
    ("2261", "Parkings", 2),
    ("2281", "Terrains  - immeubles de placement", 2),
    ("2285", "Terrains des logements affectés au personnel", 2),
    ("2286", "Terrains de location - acquisition", 2),
    ("2288", "Divers terrains", 2),
    ("2291", "Terrains agricoles et forestiers", 2),
    ("2292", "Terrains nus", 2),
    ("2295", "Terrains de  carrières - tréfonds", 2),
    ("2298", "Autres terrains", 2),
    ("2311", "Bâtiments industriels", 2),
    ("2312", "Bâtiments agricoles", 2),
    ("2313", "Bâtiments administratifs et commerciaux", 2),
    ("2314", "Bâtiments affectés au logement du personnel", 2),
    ("2315", "Bâtiments - immeubles de placement", 2),
    ("2316", "Bâtiments de location - acquisition", 2),
    ("2321", "Bâtiments industriels", 2),
    ("2322", "Bâtiments agricoles", 2),
    ("2323", "Bâtiments administratifs et commerciaux", 2),
    ("2324", "Bâtiments affectés au logement du personnel", 2),
    ("2325", "Bâtiments - immeubles de placement", 2),
    ("2326", "Bâtiments de location - acquisition", 2),
    ("2331", "Voies de terre", 2),
    ("2332", "Voies de fer", 2),
    ("2333", "Voies d’eau", 2),
    ("2334", "Barrages, Digues", 2),
    ("2335", "Pistes d’aérodrome", 2),
    ("2338", "Autres ouvrages d’infrastructures", 2),
    ("2341", "Installations complexes spécialisées sur sol propre", 2),
    ("2342", "Installations complexes spécialisées sur sol d’autrui", 2),
    ("2343", "Installations à caractère spécifique sur sol propre", 2),
    ("2344", "Installations à caractère spécifique sur sol d’autrui", 2),
    ("2345", "Aménagements et agencements des bâtiments", 2),
    ("2351", "Installations générales", 2),
    ("2358", "Autres aménagements de bureaux", 2),
    ("2391", "Bâtiments en cours", 2),
    ("2392", "Installations en cours", 2),
    ("2393", "Ouvrages d’infrastructure en cours", 2),
    ("2394", "Aménagements, agencements et installations techniques  en cours", 2),
    ("2395", "Aménagements de bureaux en cours", 2),
    ("2398", "Autres installations et agencements en cours", 2),
    ("2411", "Matériel industriel", 2),
    ("2412", "Outillage industriel", 2),
    ("2413", "Matériel commercial", 2),
    ("2414", "Outillage commercial", 2),
    ("2416", "Matériel et outillage industriel et commercial de location – acquisition", 2),
    ("2421", "Matériel agricole", 2),
    ("2422", "Outillage agricole", 2),
    ("2426", "Matériel et outillage agricole de location – acquisition", 2),
    ("2441", "Matériel de bureau", 2),
    ("2442", "Matériel informatique", 2),
    ("2443", "Matériel bureautique", 2),
    ("2444", "Mobilier de bureau", 2),
    ("2445", "Matériel et mobilier - immeubles de placement", 2),
    ("2446", "Matériel et mobilier de location - acquisition", 2),
    ("2447", "Matériel et mobilier des logements du personnel", 2),
    ("2451", "Matériel automobile", 2),
    ("2452", "Matériel ferroviaire", 2),
    ("2453", "Matériel fluvial, lagunaire", 2),
    ("2454", "Matériel naval", 2),
    ("2455", "Matériel aérien", 2),
    ("2456", "Matériel de transport de location - acquisition", 2),
    ("2457", "Matériel hippomobile", 2),
    ("2458", "Autres matériels de transport", 2),
    ("2461", "Cheptel, animaux de trait", 2),
    ("2462", "Cheptel, animaux reproducteurs", 2),
    ("2463", "Animaux de garde", 2),
    ("2465", "Plantations agricoles", 2),
    ("2468", "Autres actifs biologiques", 2),
    ("2471", "Agencements et aménagements du matériel", 2),
    ("2472", "Agencements et aménagements des actifs biologiques", 2),
    ("2478", "Autres agencements, aménagements du matériel et actifs biologiques", 2),
    ("2481", "Collections et œuvres d’art", 2),
    ("2488", "Divers matériels et mobiliers", 2),
    ("2491", "Matériel et outillage industriel et commercial", 2),
    ("2492", "Matériel et outillage agricole", 2),
    ("2493", "Matériel d’emballage récupérable et identifiable", 2),
    ("2494", "Matériel et mobilier de bureau", 2),
    ("2495", "Matériel de transport", 2),
    ("2496", "Actifs biologiques", 2),
    ("2497", "Agencements et aménagements du matériel et des actifs biologiques", 2),
    ("2498", "Autres matériels et actifs biologiques", 2),
    ("2711", "Prêts participatifs", 2),
    ("2712", "Prêts aux associés", 2),
    ("2713", "Billets de fonds", 2),
    ("2714", "Créances de location-financement", 2),
    ("2715", "Titres prêtés", 2),
    ("2718", "Autres prêts et créances", 2),
    ("2721", "Prêts immobiliers", 2),
    ("2722", "Prêts mobiliers et d’installation", 2),
    ("2728", "Autres prêts au personnel", 2),
    ("2731", "Retenues de garantie", 2),
    ("2733", "Fonds réglementé", 2),
    ("2734", "Créances sur le concédant", 2),
    ("2738", "Autres créances sur l’Etat", 2),
    ("2741", "Titres immobilisés de l’activité de portefeuille (T.I.A.P.)", 2),
    ("2742", "Titres participatifs", 2),
    ("2743", "Certificats d’investissement", 2),
    ("2744", "Parts de fonds commun de placement (F.C.P.)", 2),
    ("2745", "Obligations", 2),
    ("2746", "Actions ou parts propres", 2),
    ("2748", "Autres titres immobilisés", 2),
    ("2751", "Dépôts pour loyers d’avance", 2),
    ("2752", "Dépôts pour l’électricité", 2),
    ("2753", "Dépôts pour l’eau", 2),
    ("2754", "Dépôts pour le gaz", 2),
    ("2755", "Dépôts pour le téléphone, le télex, la télécopie", 2),
    ("2756", "Cautionnements sur marchés publics", 2),
    ("2757", "Cautionnements sur autres opérations", 2),
    ("2758", "Autres dépôts et cautionnements", 2),
    ("2761", "Prêts et créances non commerciales", 2),
    ("2762", "Prêts au personnel", 2),
    ("2763", "Créances sur l'Etat", 2),
    ("2764", "Titres immobilisés", 2),
    ("2765", "Dépôts et cautionnements versés", 2),
    ("2766", "Créances de location-financement", 2),
    ("2767", "Créances rattachées à des participations", 2),
    ("2768", "Immobilisations financières diverses", 2),
    ("2771", "Créances rattachées à des participations (groupe)", 2),
    ("2772", "Créances rattachées à des participations (hors groupe)", 2),
    ("2773", "Créances rattachées à des sociétés en participation", 2),
    ("2774", "Avances à des Groupements d'intérêt économique (G.I.E.)", 2),
    ("2781", "Créances diverses groupe", 2),
    ("2782", "Créances diverses hors groupe", 2),
    ("2784", "Banques dépôts à terme", 2),
    ("2785", "Or et métaux précieux (1)", 2),
    ("2788", "Autres immobilisations financières", 2),
    ("2811", "Amortissements des frais de développement", 2),
    ("2812", "Amortissements des brevets, licences, concessions et droits similaires", 2),
    ("2813", "Amortissements des logiciels et sites internet", 2),
    ("2814", "Amortissements des marques", 2),
    ("2815", "Amortissements du fonds commercial", 2),
    ("2816", "Amortissements du droit au bail", 2),
    ("2817", "Amortissements des investissements de création", 2),
    ("2818", "Amortissements des autres droits et valeurs incorporels", 2),
    ("2824", "Amortissements des travaux de mise en valeur des terrains", 2),
    ("2831", "Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre", 2),
    ("2832", "Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d'autrui", 2),
    ("2833", "Amortissements des ouvrages d'infrastructure", 2),
    ("2834", "Amortissements des aménagements, agencements et installations techniques", 2),
    ("2835", "Amortissements des aménagements de bureaux", 2),
    ("2837", "Amortissements des bâtiments industriels, agricoles et commerciaux mis en concession", 2),
    ("2838", "Amortissements des autres installations et agencements", 2),
    ("2841", "Amortissements du matériel et outillage industriel et commercial", 2),
    ("2842", "Amortissements du matériel et outillage agricole", 2),
    ("2843", "Amortissements du matériel d'emballage récupérable et identifiable", 2),
    ("2844", "Amortissements du matériel et mobilier", 2),
    ("2845", "Amortissements du matériel de transport", 2),
    ("2846", "Amortissements des actifs biologiques", 2),
    ("2847", "Amortissements des agencements, aménagements du matériel et des actifs biologiques", 2),
    ("2848", "Amortissements des autres matériels", 2),
    ("2911", "Dépréciations des frais de développement", 2),
    ("2912", "Dépréciations des brevets, licences, concessions  et droits similaires", 2),
    ("2913", "Dépréciations des logiciels et sites internet", 2),
    ("2914", "Dépréciations des marques", 2),
    ("2915", "Dépréciations du fonds commercial", 2),
    ("2916", "Dépréciations du droit au bail", 2),
    ("2917", "Dépréciations des investissements de création", 2),
    ("2918", "Dépréciations des autres droits et valeurs incorporels", 2),
    ("2919", "Dépréciations des immobilisations incorporelles en cours", 2),
    ("2921", "Dépréciations des terrains agricoles et forestiers", 2),
    ("2922", "Dépréciations des terrains nus", 2),
    ("2923", "Dépréciations des terrains bâtis", 2),
    ("2924", "Dépréciations des travaux de mise en valeur des terrains", 2),
    ("2925", "Dépréciations des terrains de carrières-tréfonds", 2),
    ("2926", "Dépréciations des terrains aménagés", 2),
    ("2927", "Dépréciations des terrains mis en concession", 2),
    ("2928", "Dépréciations des autres terrains", 2),
    ("2929", "Dépréciations des aménagements de terrains en cours", 2),
    ("2931", "Dépréciations des bâtiments industriels, agricoles, administratifs et commerciaux", 2),
    ("2932", "Dépréciations des bâtiments industriels, agricoles, administratifs et commerciaux", 2),
    ("2933", "Dépréciations des ouvrages d'infrastructures", 2),
    ("2934", "Dépréciations des aménagements, agencements et installations techniques", 2),
    ("2935", "Dépréciations des aménagements de bureaux", 2),
    ("2937", "Dépréciations des bâtiments industriels, agricoles et commerciaux", 2),
    ("2938", "Dépréciations des autres installations et agencements", 2),
    ("2939", "Dépréciations des bâtiments et installations en cours", 2),
    ("2941", "Dépréciations du matériel et outillage industriel et commercial", 2),
    ("2942", "Dépréciations du matériel et outillage agricole", 2),
    ("2943", "Dépréciations du matériel d'emballage récupérable et identifiable", 2),
    ("2944", "Dépréciations du matériel et mobilier", 2),
    ("2945", "Dépréciations du matériel de transport", 2),
    ("2946", "Dépréciations des actifs biologiques", 2),
    ("2947", "Dépréciations des agencements, aménagements du matériel et des actifs biologiques", 2),
    ("2948", "Dépréciations des autres matériels", 2),
    ("2949", "Dépréciations de matériel en cours", 2),
    ("2951", "Dépréciations des avances et acomptes versés sur immobilisations incorporelles", 2),
    ("2952", "Dépréciations des avances et acomptes versés sur immobilisations corporelles", 2),
    ("2961", "Dépréciations des titres de participation dans des entités sous contrôle exclusif", 2),
    ("2962", "Dépréciations des titres de participation dans des entités sous contrôle conjoint", 2),
    ("2963", "Dépréciations des titres de participation dans des entités conférant une influence notable", 2),
    ("2965", "Dépréciations des participations dans des organismes professionnels", 2),
    ("2966", "Dépréciations des parts dans des GIE", 2),
    ("2968", "Dépréciations des autres titres de participation", 2),
    ("2971", "Dépréciations des prêts et créances", 2),
    ("2972", "Dépréciations des prêts au personnel", 2),
    ("2973", "Dépréciations des créances sur l'Etat", 2),
    ("2974", "Dépréciations des titres immobilisés", 2),
    ("2975", "Dépréciations des dépôts et cautionnements versés", 2),
    ("2977", "Dépréciations des créances rattachées à des participations et avances à des GIE", 2),
    ("2978", "Dépréciations des créances financières diverses", 2),
    ("3111", "Marchandises A1", 3),
    ("3112", "Marchandises A2", 3),
    ("3121", "Marchandises B1", 3),
    ("3122", "Marchandises B2", 3),
    ("3131", "Animaux", 3),
    ("3132", "Végétaux", 3),
    ("3351", "Emballages perdus", 3),
    ("3352", "Emballages récupérables non identifiables", 3),
    ("3353", "Emballages à usage mixte", 3),
    ("3358", "Autres emballages", 3),
    ("3411", "Produits en cours P1", 3),
    ("3412", "Produits en cours P2", 3),
    ("3421", "Travaux en cours T1", 3),
    ("3422", "Travaux en cours T2", 3),
    ("3431", "Produits intermédiaires A", 3),
    ("3432", "Produits intermédiaires B", 3),
    ("3441", "Produits résiduels A", 3),
    ("3442", "Produits résiduels B", 3),
    ("3451", "Animaux", 3),
    ("3452", "Végétaux", 3),
    ("3511", "Etudes en cours E1", 3),
    ("3512", "Etudes en cours E2", 3),
    ("3521", "Prestations de services S1", 3),
    ("3522", "Prestations de services S2", 3),
    ("3631", "Animaux", 3),
    ("3632", "Végétaux", 3),
    ("3638", "Autres stocks (activités annexes)", 3),
    ("3711", "Produits intermédiaires A", 3),
    ("3712", "Produits intermédiaires B", 3),
    ("3721", "Déchets", 3),
    ("3722", "Rebuts", 3),
    ("3723", "Matières de récupération", 3),
    ("3731", "Animaux", 3),
    ("3732", "Végétaux", 3),
    ("3738", "Autres stocks (activités annexes)", 3),
    ("3871", "Stock en consignation", 3),
    ("3872", "Stock en dépôt", 3),
    ("4011", "Fournisseurs", 4),
    ("4012", "Fournisseurs Groupe", 4),
    ("4013", "Fournisseurs sous-traitants", 4),
    ("4016", "Fournisseurs, réserve de propriété", 4),
    ("4017", "Fournisseurs, retenues de garantie", 4),
    ("4021", "Fournisseurs, Effets à payer", 4),
    ("4022", "Fournisseurs - Groupe, Effets à payer", 4),
    ("4023", "Fournisseurs sous-traitants, Effets à payer", 4),
    ("4041", "Fournisseurs dettes en compte, immobilisations incorporelles", 4),
    ("4042", "Fournisseurs dettes en compte, immobilisations corporelles", 4),
    ("4046", "Fournisseurs effets à payer, immobilisations incorporelles", 4),
    ("4047", "Fournisseurs effets à payer, immobilisations corporelles", 4),
    ("4081", "Fournisseurs", 4),
    ("4082", "Fournisseurs - Groupe", 4),
    ("4083", "Fournisseurs sous-traitants", 4),
    ("4086", "Fournisseurs, intérêts courus", 4),
    ("4091", "Fournisseurs avances et acomptes versés", 4),
    ("4092", "Fournisseurs - Groupe avances et acomptes versés", 4),
    ("4093", "Fournisseurs sous-traitants avances et acomptes versés", 4),
    ("4094", "Fournisseurs créances pour emballages et matériels à rendre", 4),
    ("4098", "Fournisseurs, rabais, remises, ristournes et autres avoirs à obtenir", 4),
    ("4111", "Clients", 4),
    ("4112", "Clients - Groupe", 4),
    ("4114", "Clients, Etat et Collectivités publiques", 4),
    ("4115", "Clients, organismes internationaux", 4),
    ("4116", "Clients, réserve de propriété", 4),
    ("4117", "Clients, retenues de garantie", 4),
    ("4118", "Clients, dégrèvement de Taxes sur la Valeur Ajoutée (T.V.A.)", 4),
    ("4121", "Clients, Effets à recevoir", 4),
    ("4122", "Clients - Groupe, Effets à recevoir", 4),
    ("4124", "Etat et Collectivités publiques, Effets à recevoir", 4),
    ("4125", "Organismes Internationaux, Effets à recevoir", 4),
    ("4131", "Clients, chèques impayés", 4),
    ("4132", "Clients, Effets impayés", 4),
    ("4133", "Clients, cartes de crédit impayées", 4),
    ("4138", "Clients, autres valeurs impayées", 4),
    ("4141", "Créances en compte, immobilisations incorporelles", 4),
    ("4142", "Créances en compte, immobilisations corporelles", 4),
    ("4146", "Effets à recevoir, immobilisations incorporelles", 4),
    ("4147", "Effets à recevoir, immobilisations corporelles", 4),
    ("4161", "Créances litigieuses", 4),
    ("4162", "Créances douteuses", 4),
    ("4181", "Clients, factures à établir", 4),
    ("4186", "Clients, intérêts courus", 4),
    ("4191", "Clients, avances et acomptes reçus", 4),
    ("4192", "Clients - Groupe, avances et acomptes reçus", 4),
    ("4194", "Clients, dettes pour emballages et matériels consignés", 4),
    ("4198", "Clients, rabais, remises, ristournes et autres avoirs à accorder", 4),
    ("4211", "Personnel, avances", 4),
    ("4212", "Personnel, acomptes", 4),
    ("4213", "Frais avancés et fournitures au personnel", 4),
    ("4231", "Personnel, oppositions", 4),
    ("4232", "Personnel, saisies-arrêts", 4),
    ("4233", "Personnel, avis à tiers détenteur", 4),
    ("4241", "Assistance médicale", 4),
    ("4242", "Allocations familiales", 4),
    ("4245", "Organismes sociaux rattachés à l'entité", 4),
    ("4248", "Autres oeuvres sociales internes", 4),
    ("4251", "Délégués du personnel", 4),
    ("4252", "Syndicats et Comités d'entreprises, d'Etablissement", 4),
    ("4258", "Autres représentants du personnel", 4),
    ("4261", "Participation aux bénéfices", 4),
    ("4264", "Participation au capital", 4),
    ("4281", "Dettes provisionnées pour congés à payer", 4),
    ("4286", "Autres charges à payer", 4),
    ("4287", "Produits à recevoir", 4),
    ("4311", "Prestations familiales", 4),
    ("4312", "Accidents de travail", 4),
    ("4313", "Caisse de retraite obligatoire", 4),
    ("4314", "Caisse de retraite facultative", 4),
    ("4318", "Autres cotisations sociales", 4),
    ("4331", "Mutuelle", 4),
    ("4332", "Assurances Retraite", 4),
    ("4333", "Assurances et organismes de santé", 4),
    ("4334", "T.V.A. facturée sur production livrée à soi-même", 4),
    ("4335", "T.V.A. sur factures à établir", 4),
    ("4381", "Charges sociales sur gratifications à payer", 4),
    ("4382", "Charges sociales sur congés à payer", 4),
    ("4386", "Autres charges à payer", 4),
    ("4387", "Produits à recevoir", 4),
    ("4421", "Impôts et taxes d'Etat", 4),
    ("4422", "Impôts et taxes pour les collectivités publiques", 4),
    ("4423", "Impôts et taxes recouvrables sur des obligataires", 4),
    ("4424", "Impôts et taxes recouvrables sur des associés", 4),
    ("4426", "Droits de douane", 4),
    ("4428", "Autres impôts et taxes", 4),
    ("4431", "T.V.A. facturée sur ventes", 4),
    ("4432", "T.V.A. facturée sur prestations de services", 4),
    ("4433", "T.V.A. facturée sur travaux", 4),
    ("4441", "Etat, T.V.A. due", 4),
    ("4445", "Etat, dégrèvement T.V.A.", 4),
    ("4449", "Etat, crédit de T.V.A. à reporter", 4),
    ("4451", "T.V.A. récupérable sur immobilisations", 4),
    ("4452", "T.V.A. récupérable sur achats", 4),
    ("4453", "T.V.A. récupérable sur transport", 4),
    ("4454", "T.V.A. récupérable sur services extérieurs et autres charges", 4),
    ("4455", "T.V.A. récupérable sur factures non parvenues", 4),
    ("4456", "T.V.A. transférée par d'autres entités", 4),
    ("4471", "Impôt Général sur le revenu", 4),
    ("4472", "Impôts sur salaires", 4),
    ("4473", "Contribution nationale", 4),
    ("4474", "Contribution nationale de solidarité", 4),
    ("4478", "Autres impôts et contributions", 4),
    ("4486", "Charges à payer", 4),
    ("4487", "Produits à recevoir", 4),
    ("4491", "Etat, obligations cautionnées", 4),
    ("4492", "Etat, avances et acomptes versés sur impôts", 4),
    ("4493", "Etat, fonds de dotation à recevoir", 4),
    ("4494", "Etat, subventions d'investissement à recevoir", 4),
    ("4495", "Etat, subventions d'exploitation à recevoir", 4),
    ("4496", "Etat, subventions d'équilibre à recevoir", 4),
    ("4497", "Etat, avances sur subventions", 4),
    ("4499", "Etat, fonds réglementé provisionné", 4),
    ("4581", "Organismes internationaux, fonds de dotation à recevoir", 4),
    ("4582", "Organismes internationaux, subventions à recevoir", 4),
    ("4611", "Apporteurs, apports en nature", 4),
    ("4612", "Apporteurs, apports en numéraire", 4),
    ("4613", "Apporteurs, capital appelé, non versé", 4),
    ("4614", "Apporteurs, compte d’apport, opérations de restructuration (fusion…)", 4),
    ("4615", "Apporteurs, versements reçus sur augmentation de capital", 4),
    ("4616", "Apporteurs, versements anticipés", 4),
    ("4617", "Apporteurs défaillants", 4),
    ("4618", "Apporteurs, titres à échanger", 4),
    ("4619", "Apporteurs, capital à rembourser", 4),
    ("4621", "Principal", 4),
    ("4626", "Intérêts courus", 4),
    ("4631", "Opérations courantes", 4),
    ("4636", "Intérêts courus", 4),
    ("4711", "Débiteurs divers", 4),
    ("4712", "Créditeurs divers", 4),
    ("4713", "Obligataires", 4),
    ("4715", "Rémunérations d’administrateurs non associés", 4),
    ("4716", "Compte d’affacturage et de titrisation", 4),
    ("4717", "Débiteurs divers - retenues de garantie", 4),
    ("4718", "Apport, compte de fusion et opérations assimilées", 4),
    ("4719", "Bons de souscription d’actions et d’obligations", 4),
    ("4721", "Créances sur cessions de titres de placement", 4),
    ("4726", "Versements restant à effectuer sur titres de placement non libérés", 4),
    ("4731", "Mandants", 4),
    ("4732", "Mandataires", 4),
    ("4733", "Commettants", 4),
    ("4734", "Commissionnaires", 4),
    ("4739", "Etat, Collectivités publiques, fonds global d’allocation", 4),
    ("4746", "Compte de répartition périodique des charges", 4),
    ("4747", "Compte de répartition périodique des produits", 4),
    ("4751", "Compte-actif", 4),
    ("4752", "Compte-passif", 4),
    ("4781", "Diminution des créances d’exploitation et HAO", 4),
    ("4782", "Diminution des créances financières", 4),
    ("4783", "Augmentation des dettes d’exploitation et HAO", 4),
    ("4784", "Augmentation des dettes financières", 4),
    ("4786", "Différences d’évaluation sur instruments de trésorerie", 4),
    ("4788", "Différences compensées par couverture de change", 4),
    ("4791", "Augmentation des créances d’exploitation et HAO", 4),
    ("4792", "Augmentation des créances financières", 4),
    ("4793", "Diminution des dettes d’exploitation et HAO", 4),
    ("4794", "Diminution des dettes financières", 4),
    ("4797", "Différences d’évaluation sur instruments de trésorerie", 4),
    ("4798", "Différences compensées par couverture de change", 4),
    ("4811", "Immobilisations incorporelles", 4),
    ("4812", "Immobilisations corporelles", 4),
    ("4813", "Versements restant à effectuer sur titres de participation et titres immobilisés non libérés", 4),
    ("4816", "Réserve de propriété (3)", 4),
    ("4817", "Retenues de garantie  (3)", 4),
    ("4818", "Factures non parvenues (3)", 4),
    ("4821", "Immobilisations incorporelles", 4),
    ("4822", "Immobilisations corporelles", 4),
    ("4851", "En compte, immobilisations incorporelles", 4),
    ("4852", "En compte, immobilisations corporelles", 4),
    ("4853", "Effets à recevoir, immobilisations incorporelles", 4),
    ("4854", "Effets à recevoir, immobilisations corporelles", 4),
    ("4855", "Effets escomptés non échus", 4),
    ("4856", "Immobilisations financières", 4),
    ("4857", "Retenues de garantie", 4),
    ("4858", "Factures à établir", 4),
    ("4911", "Créances litigieuses", 4),
    ("4912", "Créances douteuses", 4),
    ("4962", "Associés, comptes courants", 4),
    ("4963", "Associés, opérations faites en commun et GIE", 4),
    ("4966", "Groupe, comptes courants", 4),
    ("4985", "Créances sur cessions d'immobilisations", 4),
    ("4986", "Créances sur cessions de titres de placement", 4),
    ("4988", "Autres créances H.A.O.", 4),
    ("4991", "Sur opérations d'exploitation", 4),
    ("4998", "Sur opérations H.A.O.", 4),
    ("5011", "Titres du Trésor à court terme", 5),
    ("5012", "Titres d'organismes financiers", 5),
    ("5013", "Bons de caisse à court terme", 5),
    ("5016", "Frais d’acquisition des titres de Trésor et bons de caisse", 5),
    ("5021", "Actions ou parts propres", 5),
    ("5022", "Actions cotées", 5),
    ("5023", "Actions non cotées", 5),
    ("5024", "Actions démembrées (certificats d'investissement ; droits de vote)", 5),
    ("5025", "Autres actions", 5),
    ("5026", "Frais d’acquisition des actions", 5),
    ("5031", "Obligations émises par l'entité et rachetées par elle", 5),
    ("5032", "Obligations cotées", 5),
    ("5033", "Obligations non cotées", 5),
    ("5035", "Autres obligations", 5),
    ("5036", "Frais d’acquisition des obligations", 5),
    ("5042", "Bons de souscription d'actions", 5),
    ("5043", "Bons de souscription d'obligations", 5),
    ("5061", "Titres du Trésor et bons de caisse à court terme", 5),
    ("5062", "Actions", 5),
    ("5063", "Obligations", 5),
    ("5181", "Warrants", 5),
    ("5182", "Billets de fonds", 5),
    ("5185", "Chèques de voyage", 5),
    ("5186", "Coupons échus", 5),
    ("5187", "Intérêts échus des obligations", 5),
    ("5211", "Banques en monnaie nationale", 5),
    ("5215", "Banques en devises", 5),
    ("5261", "Banque, intérêts courus charges à payer", 5),
    ("5267", "Banque, intérêts courus produits à recevoir", 5),
    ("5711", "Caisse en monnaie nationale", 5),
    ("5712", "Caisse en devises", 5),
    ("5721", "en monnaie nationale", 5),
    ("5722", "en devises", 5),
    ("5731", "en monnaie nationale", 5),
    ("5732", "en devises", 5),
    ("6011", "dans la Région (5)", 6),
    ("6012", "hors Région (5)", 6),
    ("6013", "aux entités du groupe dans la Région", 6),
    ("6014", "aux entités du groupe hors Région", 6),
    ("6015", "frais sur achats (6)", 6),
    ("6019", "Rabais, Remises et Ristournes obtenus (non ventilés)", 6),
    ("6021", "dans la Région (5)", 6),
    ("6022", "hors Région (5)", 6),
    ("6023", "aux entités du groupe dans la Région", 6),
    ("6024", "aux entités du groupe hors Région", 6),
    ("6025", "frais sur achats (6)", 6),
    ("6029", "Rabais, Remises et Ristournes obtenus (non ventilés)", 6),
    ("6031", "Variations des stocks de marchandises", 6),
    ("6032", "Variations des stocks de matières premières et fournitures liées", 6),
    ("6033", "Variations des stocks d'autres approvisionnements", 6),
    ("6041", "Matières consommables", 6),
    ("6042", "Matières combustibles", 6),
    ("6043", "Produits d'entretien", 6),
    ("6044", "Fournitures d'atelier et d'usine", 6),
    ("6045", "frais sur achats (6)", 6),
    ("6046", "Fournitures de magasin", 6),
    ("6047", "Fournitures de bureau", 6),
    ("6049", "Rabais, Remises et Ristournes obtenus (non ventilés)", 6),
    ("6051", "Fournitures non stockables -Eau", 6),
    ("6052", "Fournitures non stockables - Electricité", 6),
    ("6053", "Fournitures non stockables – Autres énergies", 6),
    ("6054", "Fournitures d'entretien non stockables", 6),
    ("6055", "Fournitures de bureau non stockables", 6),
    ("6056", "Achats de petit matériel et outillage", 6),
    ("6057", "Achats d'études et prestations de services", 6),
    ("6058", "Achats de travaux, matériels et équipements", 6),
    ("6059", "Rabais, Remises et Ristournes obtenus (non ventilés)", 6),
    ("6081", "Emballages perdus", 6),
    ("6082", "Emballages récupérables non identifiables", 6),
    ("6083", "Emballages à usage mixte", 6),
    ("6085", "frais sur achats (6)", 6),
    ("6089", "Rabais, Remises et Ristournes obtenus (non ventilés)", 6),
    ("6181", "Voyages et déplacements", 6),
    ("6182", "Transports entre établissements ou chantiers", 6),
    ("6183", "Transports administratifs", 6),
    ("6221", "Locations de terrains", 6),
    ("6222", "Locations de bâtiments", 6),
    ("6223", "Locations de matériels et outillages", 6),
    ("6224", "Malis sur emballages", 6),
    ("6225", "Locations d'emballages", 6),
    ("6226", "Fermages et loyers du foncier", 6),
    ("6228", "Locations et charges locatives diverses", 6),
    ("6232", "Crédit-bail immobilier", 6),
    ("6233", "Crédit-bail mobilier", 6),
    ("6234", "Location-vente", 6),
    ("6238", "Autres contrats de location-acquisition", 6),
    ("6241", "Entretien et réparations des biens immobiliers", 6),
    ("6242", "Entretien et réparations des biens mobiliers", 6),
    ("6243", "Maintenance", 6),
    ("6244", "Charges de démantèlement et remise en état", 6),
    ("6248", "Autres entretiens et réparations", 6),
    ("6251", "Assurances multirisques", 6),
    ("6252", "Assurances matériel de transport", 6),
    ("6253", "Assurances risques d'exploitation", 6),
    ("6254", "Assurances responsabilité du producteur", 6),
    ("6255", "Assurances insolvabilité clients", 6),
    ("6257", "Assurances transport sur ventes", 6),
    ("6258", "Autres primes d'assurances", 6),
    ("6261", "Etudes et recherches", 6),
    ("6265", "Documentation générale", 6),
    ("6266", "Documentation technique", 6),
    ("6271", "Annonces, insertions", 6),
    ("6272", "Catalogues, imprimés publicitaires", 6),
    ("6273", "Echantillons", 6),
    ("6274", "Foires et expositions", 6),
    ("6275", "Publications", 6),
    ("6276", "Cadeaux à la clientèle", 6),
    ("6277", "Frais de colloques, séminaires, conférences", 6),
    ("6278", "Autres charges de publicité et relations publiques", 6),
    ("6281", "Frais de téléphone", 6),
    ("6282", "Frais de télex", 6),
    ("6283", "Frais de télécopie", 6),
    ("6288", "Autres frais de télécommunications", 6),
    ("6311", "Frais sur titres (vente, garde)", 6),
    ("6312", "Frais sur effets", 6),
    ("6313", "Location de coffres", 6),
    ("6314", "Commissions d'affacturage et de titrisation", 6),
    ("6315", "Commissions sur cartes de crédit", 6),
    ("6316", "Frais d'émission d'emprunts", 6),
    ("6317", "Frais sur instruments monnaie électronique", 6),
    ("6318", "Autres frais bancaires", 6),
    ("6322", "Commissions et courtages sur ventes", 6),
    ("6324", "Honoraires des professions règlementées", 6),
    ("6325", "Frais d'actes et de contentieux", 6),
    ("6326", "Rémunérations d’affacturage et de titrisation", 6),
    ("6327", "Rémunérations des autres prestataires de services", 6),
    ("6328", "Divers frais", 6),
    ("6342", "Redevances pour brevets, licences", 6),
    ("6343", "Redevances pour logiciels", 6),
    ("6344", "Redevances pour marques", 6),
    ("6345", "Redevances pour sites  internet", 6),
    ("6346", "Redevances pour concessions, droits et valeurs similaires", 6),
    ("6351", "Cotisations", 6),
    ("6358", "Concours divers", 6),
    ("6371", "Personnel intérimaire", 6),
    ("6372", "Personnel détaché ou prêté à l'entité", 6),
    ("6381", "Frais de recrutement du personnel", 6),
    ("6382", "Frais de déménagement", 6),
    ("6383", "Réceptions", 6),
    ("6384", "Missions", 6),
    ("6385", "Charges de copropriété", 6),
    ("6388", "Charges externes diverses", 6),
    ("6411", "Impôts fonciers et taxes annexes", 6),
    ("6412", "Patentes, licences et taxes annexes", 6),
    ("6413", "Taxes sur appointements et salaires", 6),
    ("6414", "Taxes d'apprentissage", 6),
    ("6415", "Formation professionnelle continue", 6),
    ("6418", "Autres impôts et taxes directs", 6),
    ("6461", "Droits de mutation", 6),
    ("6462", "Droits de timbre", 6),
    ("6463", "Taxes sur les véhicules de société", 6),
    ("6464", "Vignettes", 6),
    ("6468", "Autres droits d'enregistrement", 6),
    ("6471", "Pénalités d'assiette, impôts directs", 6),
    ("6472", "Pénalités d'assiette, impôts indirects", 6),
    ("6473", "Pénalités de recouvrement, impôts directs", 6),
    ("6474", "Pénalités de recouvrement, impôts indirects", 6),
    ("6478", "Autres pénalités et amendes fiscales", 6),
    ("6511", "Clients", 6),
    ("6515", "Autres débiteurs", 6),
    ("6521", "Quote-part transférée de bénéfices (comptabilité du gérant)", 6),
    ("6525", "Pertes imputées par transfert (comptabilité des associés non gérants)", 6),
    ("6541", "Immobilisations incorporelles", 6),
    ("6542", "Immobilisations corporelles", 6),
    ("6581", "Indemnités de fonction et autres rémunérations d'administrateurs", 6),
    ("6582", "Dons", 6),
    ("6583", "Mécénat", 6),
    ("6588", "Autres charges diverses", 6),
    ("6591", "sur risques à court terme", 6),
    ("6593", "sur stocks", 6),
    ("6594", "sur créances", 6),
    ("6598", "Autres charges pour  dépréciations et provisions pour risques à court terme", 6),
    ("6611", "Appointements salaires et commissions", 6),
    ("6612", "Primes et gratifications", 6),
    ("6613", "Congés payés", 6),
    ("6614", "Indemnités de préavis, de licenciement et de recherche d'embauche", 6),
    ("6615", "Indemnités de maladie versées aux travailleurs", 6),
    ("6616", "Supplément familial", 6),
    ("6617", "Avantages en nature", 6),
    ("6618", "Autres rémunérations directes", 6),
    ("6621", "Appointements salaires et commissions", 6),
    ("6622", "Primes et gratifications", 6),
    ("6623", "Congés payés", 6),
    ("6624", "Indemnités de préavis, de licenciement et de recherche d'embauche", 6),
    ("6625", "Indemnités de maladie versées aux travailleurs", 6),
    ("6626", "Supplément familial", 6),
    ("6627", "Avantages en nature", 6),
    ("6628", "Autres rémunérations directes", 6),
    ("6631", "Indemnités de logement", 6),
    ("6632", "Indemnités de représentation", 6),
    ("6633", "Indemnités d'expatriation", 6),
    ("6634", "Indemnités de transport", 6),
    ("6638", "Autres indemnités et avantages divers", 6),
    ("6641", "Charges sociales sur rémunération du personnel national", 6),
    ("6642", "Charges sociales sur rémunération du personnel non national", 6),
    ("6661", "Rémunération du travail de l'exploitant", 6),
    ("6662", "Charges sociales", 6),
    ("6671", "Personnel intérimaire", 6),
    ("6672", "Personnel détaché ou prêté à l’entité", 6),
    ("6681", "Versements aux Syndicats et Comités d'entreprise, d'établissement", 6),
    ("6682", "Versements aux Comités d'hygiène et de sécurité", 6),
    ("6683", "Versements et contributions aux autres œuvres sociales", 6),
    ("6684", "Médecine du travail et pharmacie", 6),
    ("6685", "Assurances et organismes de santé", 6),
    ("6686", "Assurances retraite et fonds de pensions", 6),
    ("6687", "Majorations et pénalités sociales", 6),
    ("6688", "Charges sociales diverses", 6),
    ("6711", "Emprunts obligataires", 6),
    ("6712", "Emprunts auprès des établissements de crédit", 6),
    ("6713", "Dettes liées à des participations", 6),
    ("6714", "Primes de remboursement des obligations", 6),
    ("6722", "Intérêts dans loyers de location-acquisition/crédit-bail immobilier", 6),
    ("6723", "Intérêts dans loyers de location-acquisition/crédit-bail mobilier", 6),
    ("6724", "Intérêts dans loyers de location-acquisition/location-vente", 6),
    ("6728", "Intérêts dans loyers des autres locations-acquisition", 6),
    ("6741", "Avances reçues et dépôts créditeurs", 6),
    ("6742", "Comptes courants bloqués", 6),
    ("6743", "Intérêts sur obligations cautionnées", 6),
    ("6744", "Intérêts sur dettes commerciales", 6),
    ("6745", "Intérêts bancaires et sur opérations de financement (escompte…)", 6),
    ("6748", "Intérêts sur dettes diverses", 6),
    ("6771", "Pertes sur cessions de titres de placement", 6),
    ("6772", "Malis provenant d’attribution gratuite d’actions au personnel salarié et aux dirigeants", 6),
    ("6781", "sur rentes viagères", 6),
    ("6782", "sur opérations financières", 6),
    ("6784", "sur instruments de trésorerie", 6),
    ("6791", "sur risques financiers", 6),
    ("6795", "sur titres de placement", 6),
    ("6798", "Autres charges pour dépréciations et provisions pour risques à court terme financières", 6),
    ("6812", "Dotations aux amortissements des immobilisations incorporelles", 6),
    ("6813", "Dotations aux amortissements des immobilisations corporelles", 6),
    ("6911", "Dotations aux provisions pour risques et charges", 6),
    ("6913", "Dotations aux dépréciations des immobilisations incorporelles", 6),
    ("6914", "Dotations aux dépréciations des immobilisations corporelles", 6),
    ("6971", "Dotations aux provisions pour risques et charges", 6),
    ("6972", "Dotations aux dépréciations des immobilisations financières", 6),
    ("7011", "dans la Région (7)", 7),
    ("7012", "hors Région (7)", 7),
    ("7013", "aux entités du groupe dans la Région", 7),
    ("7014", "aux entités du groupe hors Région", 7),
    ("7015", "sur internet", 7),
    ("7019", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7021", "dans la Région (7)", 7),
    ("7022", "hors Région (7)", 7),
    ("7023", "aux entités du groupe dans la Région", 7),
    ("7024", "aux entités du groupe hors Région", 7),
    ("7025", "sur internet", 7),
    ("7029", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7031", "dans la Région (7)", 7),
    ("7032", "hors Région (7)", 7),
    ("7033", "aux entités du groupe dans la Région", 7),
    ("7034", "aux entités du groupe hors Région", 7),
    ("7035", "sur internet", 7),
    ("7039", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7041", "dans la Région (7)", 7),
    ("7042", "hors Région (7)", 7),
    ("7043", "aux entités du groupe dans la Région", 7),
    ("7044", "aux entités du groupe hors Région", 7),
    ("7045", "sur internet", 7),
    ("7049", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7051", "dans la Région (7)", 7),
    ("7052", "hors Région (7)", 7),
    ("7053", "aux entités du groupe dans la Région", 7),
    ("7054", "aux entités du groupe hors Région", 7),
    ("7055", "sur internet", 7),
    ("7059", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7061", "dans la Région (7)", 7),
    ("7062", "hors Région (7)", 7),
    ("7063", "aux entités du groupe dans la Région", 7),
    ("7064", "aux entités du groupe hors Région", 7),
    ("7065", "sur internet", 7),
    ("7069", "Rabais, remises, ristournes accordés (non ventilés)", 7),
    ("7071", "Ports, emballages perdus et autres frais facturés", 7),
    ("7072", "Commissions et courtages(8)", 7),
    ("7073", "Locations et redevances de location - financement (8)", 7),
    ("7074", "Bonis sur reprises et cessions d'emballages", 7),
    ("7075", "Mise à disposition de personnel (8)", 7),
    ("7076", "Redevances pour brevets, logiciels, marques et droits similaires (8)", 7),
    ("7077", "Services exploités dans l'intérêt du personnel", 7),
    ("7078", "Autres produits accessoires", 7),
    ("7181", "Versées par l'Etat et les collectivités publiques", 7),
    ("7182", "Versées par les organismes internationaux", 7),
    ("7183", "Versées par des tiers", 7),
    ("7221", "immobilisations corporelles (hors actifs biologiques)", 7),
    ("7222", "immobilisations corporelles (actifs biologiques)", 7),
    ("7341", "Produits en cours", 7),
    ("7342", "Travaux en cours", 7),
    ("7351", "Etudes en cours", 7),
    ("7352", "Prestations de services en cours", 7),
    ("7371", "Produits intermédiaires", 7),
    ("7372", "Produits résiduels", 7),
    ("7521", "Quote-part transférée de pertes (comptabilité du gérant)", 7),
    ("7525", "Bénéfices attribués par transfert (comptabilité des associés non gérants)", 7),
    ("7541", "Immobilisations incorporelles", 7),
    ("7542", "Immobilisations corporelles", 7),
    ("7581", "Indemnités de fonction et autres rémunérations d'administrateurs", 7),
    ("7582", "Indemnités d’assurances reçues", 7),
    ("7588", "Autres produits divers", 7),
    ("7591", "sur risques à court terme", 7),
    ("7593", "sur stocks", 7),
    ("7594", "sur créances", 7),
    ("7598", "sur autres charges pour dépréciations  et provisions pour risques à court terme d’exploitation", 7),
    ("7712", "Intérêts de prêts", 7),
    ("7713", "Intérêts sur créances diverses", 7),
    ("7721", "Revenus des titres de participation", 7),
    ("7722", "Revenus autres titres immobilisés", 7),
    ("7745", "Revenus des obligations", 7),
    ("7746", "Revenus des titres de placement", 7),
    ("7781", "sur rentes viagères", 7),
    ("7782", "sur opérations financières", 7),
    ("7784", "sur instruments de trésorerie", 7),
    ("7791", "sur risques financiers", 7),
    ("7795", "sur titres de placement", 7),
    ("7798", "sur autres charges pour dépréciations et provisions pour risques à court terme financières", 7),
    ("7911", "pour risques et charges", 7),
    ("7913", "des immobilisations incorporelles", 7),
    ("7914", "des immobilisations corporelles", 7),
    ("7971", "pour risques et charges", 7),
    ("7972", "des immobilisations financières", 7),
    ("8911", "Activités exercées dans l'Etat", 8),
    ("8912", "Activités exercées dans les autres Etats de la Région", 8),
    ("8913", "Activités exercées hors Région", 8),
    ("8991", "Dégrèvements", 8),
    ("8994", "Annulations pour pertes rétroactives", 8),
    ("9051", "Crédits accordés non décaissés", 9),
    ("9058", "Autres engagements de financement accordés", 9),
    ("9061", "Avals accordés", 9),
    ("9062", "Cautions, garanties accordées", 9),
    ("9063", "Hypothèques accordées", 9),
    ("9064", "Effets endossés par l'entité", 9),
    ("9068", "Autres garanties accordées", 9),
    ("9071", "Ventes de marchandises à terme", 9),
    ("9072", "Ventes à terme de devises", 9),
    ("9073", "Commandes fermes aux fournisseurs", 9),
    ("9078", "Autres engagements réciproques", 9),
    ("9081", "Annulations conditionnelles de dettes", 9),
    ("9082", "Engagements de retraite", 9),
    ("9083", "Achats avec clause de réserve de propriété", 9),
    ("9088", "Divers engagements accordés", 9),
    ("47811", "Diminution des créances d’exploitation", 4),
    ("47818", "Diminution des créances HAO", 4),
    ("47831", "Augmentation des dettes d’exploitation", 4),
    ("47838", "Augmentation des dettes HAO", 4),
    ("47911", "Augmentation des créances d’exploitation", 4),
    ("47918", "Augmentation des créances HAO", 4),
    ("47931", "Diminution des dettes d’exploitation", 4),
    ("47938", "Diminution des dettes HAO", 4),
    ("48161", "Réserve de propriété - immobilisations incorporelles", 4),
    ("48162", "Réserve de propriété - immobilisations corporelles", 4),
    ("48171", "Retenues de garantie  - immobilisations incorporelles", 4),
    ("48172", "Retenues de garantie  - immobilisations incorporelles", 4),
    ("48181", "Factures non parvenues - immobilisations incorporelles", 4),
    ("48182", "Factures non parvenues - immobilisations corporelles", 4),
]


def populate_comptes_syscohada(apps, schema_editor):
    CompteSyscohada = apps.get_model("comptabilite", "CompteSyscohada")
    objs = [
        CompteSyscohada(code=code, libelle=libelle, classe=classe)
        for code, libelle, classe in COMPTES_SYSCOHADA
    ]
    CompteSyscohada.objects.bulk_create(objs, ignore_conflicts=True)


def depopulate_comptes_syscohada(apps, schema_editor):
    CompteSyscohada = apps.get_model("comptabilite", "CompteSyscohada")
    codes = [c for c, _, _ in COMPTES_SYSCOHADA]
    CompteSyscohada.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_comptes_syscohada, depopulate_comptes_syscohada),
    ]