# Generated by Django 6.0.6 on 2026-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_populate_notes_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteannexedefinition',
            name='categorie',
            field=models.CharField(choices=[('identification', 'Page de garde / identification (saisie manuelle une fois par client)'), ('etat_financier', 'État financier principal (Bilan, Résultat, TFT — agrégation directe des comptes)'), ('note_syscohada', 'Note annexe SYSCOHADA (calculée via LigneNote)'), ('supplementaire_dgi', 'Tableau supplémentaire DGI/INS (hors norme OHADA)')], default='note_syscohada', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='noteannexedefinition',
            name='onglet_dgi',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Nom de l'onglet dans le fichier officiel DGI"),
        ),
    ]
