# Generated by Django 6.0.6 on 2026-07-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_populate_lignenote_pilotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustementNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_note', models.CharField(max_length=15, verbose_name='Code note')),
                ('libelle_ligne', models.CharField(max_length=200, verbose_name='Libellé de la rubrique')),
                ('cellule_dgi', models.CharField(help_text="Ex. 'NOTE 3A!F17'", max_length=30, verbose_name='Cellule concernée')),
                ('mode', models.CharField(choices=[('complement_residuel', 'Complément soustrait de la ligne calculée automatiquement'), ('remplacement', 'Remplace intégralement une valeur calculée (ex. prorata placement)')], default='complement_residuel', max_length=25, verbose_name="Mode d'application")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant')),
                ('commentaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Justification')),
                ('saisi_le', models.DateTimeField(auto_now_add=True, verbose_name='Saisi le')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements', to='comptabilite.balance')),
            ],
            options={
                'verbose_name': 'Ajustement manuel de note',
                'verbose_name_plural': 'Ajustements manuels de notes',
            },
        ),
    ]
