"""
Peuplement de LigneNote pour COMP-CHARGES : mapping direct compte SYSCOHADA
-> ligne exacte du tableau "ETAT COMPLEMENTAIRE N 1" (216 comptes officiels).

Decouverte cle : COMP-CHARGES est deja le tableau compte-par-compte que notre
LigneNote reconstruisait manuellement note par note. En ecrivant directement
ici (colonne G = Exercice N, colonne H = Exercice N-1), les formules DEJA
PRESENTES dans le fichier officiel (poses par le cabinet lui-meme) propagent
automatiquement vers NOTE 22, 23, 24, 25, 26, 27A, 29, 31 puis RESULTAT.
On ne doit donc JAMAIS ecrire directement dans les cellules de ces notes :
ce sont des formules (='COMP-CHARGES'!G11 etc.), pas des cellules de saisie.
"""
from django.db import migrations

REGIME = "NO"

# (compte, libelle, ligne_excel)
LIGNES_COMP_CHARGES = [
    ("6011", "Achats de marchandises dans la région", 11),
    ("6012", "Achats de marchandises hors région", 12),
    ("6013", "Achats de marchandises aux entités du groupe dans la région", 13),
    ("6014", "Achats de marchandises aux entités du groupe hors région", 14),
    ("6015", "Frais sur achats", 15),
    ("6019", "Rabais, remises et ristournes obtenus (non ventilés)", 16),
    ("6031", "Variation des stocks de marchandises", 18),
    ("6021", "Achats de matières premières et fournitures liées dans la région", 20),
    ("6022", "Achats de matières premières et fournitures liées hors région", 21),
    ("6023", "Achats de matières premières et fournitures liées aux entités du groupe dans la région", 22),
    ("6024", "Achats de matières premières et fournitures liées aux entités du groupe hors région", 23),
    ("6025", "Frais sur achats", 24),
    ("6029", "Rabais, remises et ristournes obtenus (non ventilés)", 25),
    ("6032", "Variation des stocks de matières premières et fournitures liées", 27),
    ("6041", "Matières consommables", 29),
    ("6042", "Matières combustibles", 30),
    ("6043", "Produits d'entretien", 31),
    ("6044", "Fournitures d'atelier et d'usine", 32),
    ("6045", "Frais sur achats", 33),
    ("6046", "Fournitures de magasin", 34),
    ("6047", "Fournitures de bureau", 35),
    ("6049", "Rabais, remises et ristournes obtenus (non ventilés)", 36),
    ("6051", "Fournitures non stockables-Eau", 37),
    ("6052", "Fournitures non stockables-Electricité", 38),
    ("6053", "Fournitures non stockables-Autres énergies", 39),
    ("6054", "Fournitures d'entretien non stockables", 40),
    ("6055", "Fournitures de bureau non stockables", 41),
    ("6056", "Achats de petit matériel et outillage", 42),
    ("6057", "Achats d'études et prestations de services", 43),
    ("6058", "Achats de travaux, matériels et équipements", 44),
    ("6059", "Rabais, remises et ristournes obtenus (non ventilés)", 45),
    ("6081", "Emballages perdus", 46),
    ("6082", "Emballages récupérables non identifiables", 47),
    ("6083", "Emballages à usage mixte", 48),
    ("6085", "Frais sur achats", 49),
    ("6089", "Rabais, remises et ristournes obtenus (non ventilés)", 50),
    ("6033", "Variation des stocks d'autres approvisionnements", 52),
    ("612", "Transports sur ventes", 54),
    ("613", "Transports pour le compte de tiers", 55),
    ("614", "Transports du personnel", 56),
    ("616", "Transports de plis", 57),
    ("6181", "Voyages et déplacements", 58),
    ("6182", "Transports entre établissements et chantiers", 59),
    ("6183", "Transports administratifs", 60),
    ("619", "Rabais, remises et ristournes obtenus (non ventilés)", 61),
    ("621", "Sous-traitance générale", 63),
    ("6221", "Location de terrains", 64),
    ("6222", "Location de bâtiments", 65),
    ("6223", "Location de matériels et outillages", 66),
    ("6224", "Malis sur emballages", 67),
    ("6225", "Locations d'emballages", 68),
    ("6226", "Fermages et loyers du foncier", 69),
    ("6228", "Locations  et charges locatives diverses", 70),
    ("6232", "Crédit-bail immobilier", 71),
    ("6233", "Crédit-bail mobilier", 72),
    ("6234", "Location-vente", 73),
    ("6238", "Autres contrats de location-acquisition", 85),
    ("6241", "Entretien et réparation des biens immobiliers", 86),
    ("6242", "Entretien et réparation des biens mobiliers", 87),
    ("6243", "Maintenance", 88),
    ("6244", "Charges de démentellement et remise en état", 89),
    ("6248", "Autre entretiens et réparation", 90),
    ("6251", "Assurances multirisques", 91),
    ("6252", "Assurances matériels de transport", 92),
    ("6253", "Assurances risques d'exploitation", 93),
    ("6254", "Assurances responsabilité du producteur", 94),
    ("6255", "Assurances insolvabilité clients", 95),
    ("6257", "Assurances transport sur ventes", 96),
    ("6258", "Autres primes d'assurances", 97),
    ("6261", "Etudes et recherches", 98),
    ("6265", "Documentation générale", 99),
    ("6266", "Documentation technique", 100),
    ("6271", "Annonces, insertions", 101),
    ("6272", "Catalogues, imprimés publicitaires", 102),
    ("6273", "Échantillons", 103),
    ("6274", "Foires et expositions", 104),
    ("6275", "Publications", 105),
    ("6276", "Cadeaux à la clientèle", 106),
    ("6277", "Frais de colloques, séminaires, conférences", 107),
    ("6278", "Autres charges de publicité et relations publiques", 108),
    ("6281", "Frais de téléphone", 109),
    ("6282", "Frais de télex", 110),
    ("6283", "Frais de télécopie", 111),
    ("6284", "Frais d'internet", 112),
    ("6288", "Autres frais de télécommunications", 113),
    ("6311", "Frais sur titres (vente, garde)", 114),
    ("6312", "Frais sur effets", 115),
    ("6313", "Location de coffres", 116),
    ("6314", "Commissions d'affacturage et de titrisation", 117),
    ("6315", "Commissions sur cartes de crédit", 118),
    ("6316", "Frais d'émission d'emprunts", 119),
    ("6317", "Frais sur instruments monnaie électronique", 120),
    ("6318", "Autres frais bancaires", 121),
    ("6322", "Commissions et courtages sur ventes", 122),
    ("6324", "Honoraires des professions règlementées", 123),
    ("6325", "Frais d'actes et de contentieux", 124),
    ("6326", "Rémunérations d'affacturage et de titrisation", 125),
    ("6327", "Rémunérations des autres prestataires de services", 126),
    ("6328", "Divers frais", 127),
    ("633", "Frais de formation du personnel", 128),
    ("6342", "Redevances pour brevets, licences", 129),
    ("6343", "Redevances pour logiciels", 130),
    ("6344", "Redevances pour marques", 131),
    ("6345", "Redevances pour sites internet", 132),
    ("6346", "Redevances pour concessions, droits et valeurs similaires", 133),
    ("6351", "Cotisations", 134),
    ("6358", "Concours divers", 135),
    ("6371", "Personnel intérimaire", 136),
    ("6372", "Personnel détaché ou prêté à l'entité", 137),
    ("6381", "Frais de recrutement du personnel", 138),
    ("6382", "Frais de déménagement", 139),
    ("6383", "Réceptions", 140),
    ("6384", "Missions", 141),
    ("6385", "Charges de copropriété", 142),
    ("6388", "Charges externes diverses", 143),
    ("6411", "Impôts fonciers et taxes annexes", 145),
    ("6412", "Patentes, licences et taxes annexes", 146),
    ("6413", "Taxes sur appointements et salaires", 147),
    ("6414", "Taxes d'apprentissage", 148),
    ("6415", "Formation professionnelle continue", 160),
    ("6418", "Autres impôts et taxes directs", 161),
    ("645", "Impôts et taxes indirects", 162),
    ("6461", "Droits de mutation", 163),
    ("6462", "Droits de timbre", 164),
    ("6463", "Taxes sur les véhicules de société", 165),
    ("6464", "Vignettes", 166),
    ("6468", "Autres droits d'enregistrement", 167),
    ("6471", "Pénalités d'assiette, impôts directs", 168),
    ("6472", "Pénalités d'assiette, impôts indirects", 169),
    ("6473", "Pénalités de recouvrement, impôts directs", 170),
    ("6474", "Pénalités de recouvrement, impôts indirects", 171),
    ("6478", "Autres pénalités et amendes fiscales", 172),
    ("648", "Autres impôts et taxes", 173),
    ("6511", "Pertes sur créances clients", 175),
    ("6515", "Pertes sur autres débiteurs", 176),
    ("6521", "Quote-part transférée de bénéfices (comptabilité du gérant)", 177),
    ("6525", "Pertes imputées par transfert (comptabilité des associés non gérants)", 178),
    ("6541", "Valeur comptable des cessions courantes d'immobilisations incorporelles", 179),
    ("6542", "Valeur comptable des cessions courantes d'immobilisations corporelles", 180),
    ("656", "Perte de change sur créances et dettes commerciales", 181),
    ("657", "Pénalités et amendes pénales", 182),
    ("6581", "Indemnités de fonction et autres rémunérations d'administrateurs", 183),
    ("6582", "Dons", 184),
    ("6583", "Mécénat", 185),
    ("6588", "Autres charges diverses", 186),
    ("6591", "Charges pour dépréciation et provisions d'exploitation sur risques à court terme", 187),
    ("6593", "Charges pour dépréciation et provisions pour risque à court terme d'exploitation sur stocks", 188),
    ("6594", "Charges pour dépréciation et provisions pour risque à court terme d'exploitation sur créances", 189),
    ("6598", "Autres charges pour dépréciations et provisions pour risques à court terme d'exploitation", 190),
    ("6611", "Appointements salaires et commissions versés au personnel national", 192),
    ("6612", "Primes et gratifications versées au personnel national", 193),
    ("6613", "Congés payés versés au personnel national", 194),
    ("6614", "Indemnités de préavis, de licenciement et de recherche d'embauche versées au personnel national", 195),
    ("6615", "Indemnités de maladie versées aux travailleurs nationaux", 196),
    ("6616", "Supplément familial versé au personnel national", 197),
    ("6617", "Avantages en nature du personnel national", 198),
    ("6618", "Autres rénumérations directes versées au personnel national", 199),
    ("6621", "Appointements salaires et commissions versés au personnel non national", 200),
    ("6622", "Primes et gratifications versées au personnel non national", 201),
    ("6623", "Congés payés versés au personnel non national", 202),
    ("6624", "Indemnités de préavis, de licenciement et de recherche d'embauche versées au personnel non national", 203),
    ("6625", "Indemnités de maladie versées aux travailleurs non nationaux", 204),
    ("6626", "Supplément familial versé au personnel non national", 205),
    ("6627", "Avantages en nature du personnel non national", 206),
    ("6628", "Autres rénumérations directes versées au personnel non national", 207),
    ("6631", "Indemnités forfaitaires de logement versées au personnel", 208),
    ("6632", "Indemnités forfaitaires de représentation versées au personnel", 209),
    ("6633", "Indemnités forfaitaires d'expatriation versées au personnel", 210),
    ("6634", "Indemnités forfaitaires de transport versées au personnel", 211),
    ("6638", "Autres indemnités et avantages divers versés au personnel", 212),
    ("6641", "Charges sociales sur rémunération du personnel national", 213),
    ("6642", "Charges sociales sur rémunération du personnel non national", 214),
    ("6661", "Rémunérations du travail de l'exploitant individuel", 215),
    ("6662", "Charges sociales de l'exploitant individuel", 216),
    ("6671", "Rémunérations transférée du personnel intérimaire", 217),
    ("6672", "Rémunérations transférée du personnel détaché ou prêté à l'entité", 218),
    ("6681", "Versements aux Syndicats et Comités d'entreprise, d'établissement", 219),
    ("6682", "Versements aux Comités d'hygiène et de sécurité", 220),
    ("6683", "Versements et contributions aux autres œuvres sociales", 221),
    ("6684", "Médecine du travail et pharmacie", 233),
    ("6685", "Assurances et organismes de santé", 234),
    ("6686", "Assurances retraite et fonds de pension", 235),
    ("6687", "Majorations et pénalités sociales", 236),
    ("6688", "Charges sociales diverses", 237),
    ("6711", "Intérêts des emprunts obligataires", 239),
    ("6712", "Intérêts des emprunts auprès des établissements de crédit", 240),
    ("6713", "Intérêts des dettes liées à des participations", 241),
    ("6714", "Intérêts des primes de remboursement des obligations", 242),
    ("6721", "Intérêts dans loyers de location acquisition/crédit-bail immobilier", 243),
    ("6722", "Intérêts dans loyers de location acquisition/crédit-bail mobilier", 244),
    ("6723", "Intérêts dans loyers de location acquisition/location-vente", 245),
    ("6728", "Intérêts dans loyers des autres locations acquisition", 246),
    ("673", "Escomptes accordés", 247),
    ("6741", "Intérêts sur avances reçues et dépôts créditeurs", 248),
    ("6742", "Intérêts sur Comptes courants bloqués", 249),
    ("6743", "Intérêts sur obligations cautionnées", 250),
    ("6744", "Intérêts sur dettes commerciales", 251),
    ("6745", "Intérêts bancaires et sur opérations de financement (escompte…)", 252),
    ("6748", "Intérêts sur dettes diverses", 253),
    ("675", "Escomptes des effets de commerce", 254),
    ("676", "Pertes de change financières", 255),
    ("6771", "Pertes sur cessions de titre de placement", 256),
    ("6772", "Malis provenant d’attribution gratuite d’actions au personnel salarié et aux dirigeants", 257),
    ("6781", "Pertes et charges sur rentes viagères", 258),
    ("6782", "Pertes et charges sur opérations financières", 259),
    ("6784", "Pertes et charges sur instrument de trésorerie", 260),
    ("6791", "Charges pour dépréciations et provisions sur risques financiers à court terme", 261),
    ("6795", "Charges pour dépréciations et provisions sur titres de placement", 262),
    ("6798", "Autres charges pour dépréciations et provisions pour risques à court terme financières", 263),
    ("6812", "Dotations aux amortissements des immobilisations incorporelles", 265),
    ("6813", "Dotations aux amortissements des immobilisations corporelles", 266),
    ("6911", "Dotations aux provisions pour risques et charges", 267),
    ("6913", "Dotations aux dépréciations des immobilisations incorporelles", 268),
    ("6914", "Dotations aux dépréciations des immobilisations corporelles", 269),
    ("6971", "Dotations aux provisions pour risques et charges financières", 271),
    ("6972", "Dotations aux dépréciations des immobilisations financières", 272),
]


def populate_comp_charges(apps, schema_editor):
    LigneNote = apps.get_model("comptabilite", "LigneNote")
    objs = []
    for compte, libelle, ligne_excel in LIGNES_COMP_CHARGES:
        for colonne, source in [("G", "solde_final"), ("H", "solde_initial")]:
            objs.append(LigneNote(
                regime_liasse=REGIME, code_note="COMP-CHARGES", libelle_ligne=libelle,
                prefixe_comptes=compte, source=source,
                cellule_dgi=f"COMP-CHARGES!{colonne}{ligne_excel}", ordre=ligne_excel,
            ))
    LigneNote.objects.bulk_create(objs, ignore_conflicts=True)


def depopulate_comp_charges(apps, schema_editor):
    LigneNote = apps.get_model("comptabilite", "LigneNote")
    LigneNote.objects.filter(regime_liasse=REGIME, code_note="COMP-CHARGES").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0007_ajustementnote"),  # <-- ajuste selon ton numero reel
    ]

    operations = [
        migrations.RunPython(populate_comp_charges, depopulate_comp_charges),
    ]