# Generated by Django 6.0.6 on 2026-07-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0008_populate_comp_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=15, verbose_name='N° de compte SYSCOHADA')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('taux_amortissement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'amortissement (%)")),
                ('date_mise_en_service', models.DateField(verbose_name='Date de mise en service')),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Valeur d'acquisition")),
                ('amortissements_anterieurs', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Amortissements antérieurs')),
                ('amortissements_exercice', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="Amortissements de l'exercice")),
                ('date_cession', models.DateField(blank=True, null=True, verbose_name='Date de cession')),
                ('prix_cession', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Prix de cession')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='comptabilite.balance')),
            ],
            options={
                'verbose_name': "Ligne d'immobilisation (SUPPL4)",
                'verbose_name_plural': "Lignes d'immobilisation (SUPPL4)",
                'ordering': ['compte', 'date_mise_en_service'],
            },
        ),
    ]
