# Generated by Django 6.0.6 on 2026-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_ligneimmobilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignenote',
            name='sens',
            field=models.CharField(choices=[('les_deux', 'Les deux sens (débiteur ou créditeur)'), ('debiteur', 'Seulement si le compte est débiteur'), ('crediteur', 'Seulement si le compte est créditeur')], default='les_deux', help_text="N'agréger le compte que s'il va dans ce sens. Ex. 52 en 'crediteur' → découvert (trésorerie-passif) ; 411 en 'debiteur' → clients.", max_length=10, verbose_name='Sens du solde retenu'),
        ),
        migrations.AddField(
            model_name='lignenote',
            name='signe',
            field=models.IntegerField(choices=[(1, 'Positif (+1) — actif / présentation débit-positif'), (-1, 'Négatif (−1) — passif / présentation crédit-positif')], default=1, help_text='+1 côté actif (débit-positif), −1 côté passif (crédit-positif). Le ± du report à nouveau et du résultat en découle automatiquement.', verbose_name='Signe appliqué'),
        ),
    ]
