# Generated by Django 6.0.6 on 2026-07-17 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureElectronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signatures/', verbose_name='Signature (fond transparent)')),
                ('image_originale', models.ImageField(blank=True, null=True, upload_to='signatures/originales/', verbose_name="Photo / scan d'origine")),
                ('est_active', models.BooleanField(default=True, verbose_name='Signature active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Signature électronique',
                'verbose_name_plural': 'Signatures électroniques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_original', models.FileField(upload_to='documents_signes/originals/', verbose_name='Document original')),
                ('fichier_signe', models.FileField(upload_to='documents_signes/signes/', verbose_name='Document signé')),
                ('nom_signataire', models.CharField(max_length=200, verbose_name='Nom du signataire')),
                ('consentement_signature', models.BooleanField(default=False, verbose_name='Consentement signature électronique')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_signe', models.DateTimeField(auto_now_add=True, verbose_name='Date de signature')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_signes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_signes', to='comptes.signatureelectronique', verbose_name='Signature utilisée')),
            ],
            options={
                'verbose_name': 'Document signé',
                'verbose_name_plural': 'Documents signés',
                'ordering': ['-date_signe'],
            },
        ),
    ]
