# Generated by Django 6.0.6 on 2026-07-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_delegation_signature'),
        ('pilotage', '0003_pole_fonctionnalites_urls_pole_sous_modules_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='pilotage.pole', verbose_name='Pôle'),
        ),
        migrations.AddField(
            model_name='profil',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulaires', to='pilotage.poste', verbose_name='Poste'),
        ),
    ]
