# Generated by Django 6.0.6 on 2026-07-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_profil_pole_profil_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité'),
        ),
    ]
