# Generated by Django 6.0.6 on 2026-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_profil_derniere_activite'),
        ('pilotage', '0007_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='postes_secondaires',
            field=models.ManyToManyField(blank=True, related_name='titulaires_secondaires', to='pilotage.poste', verbose_name='Postes secondaires'),
        ),
    ]
