# Generated by Django 6.0.6 on 2026-06-29 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, help_text="Photo principale de l'article (facultative).", null=True, upload_to='actualites/', verbose_name='Image de couverture')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('lien_video', models.URLField(blank=True, help_text="Facultatif. Collez ici le lien d'une vidéo à afficher dans l'article.", verbose_name='Lien vidéo (YouTube, Facebook…)')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('publie', models.BooleanField(default=False, help_text="Cochez pour rendre l'article visible sur le site. Décoché = brouillon.", verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
